//! `autumn generate job` — scaffold a `#[job]` handler, args struct,
//! `src/jobs/mod.rs` aggregator, and main.rs wiring.
//!
//! For a name like `SendWelcomeEmail`, the generator produces:
//! - `src/jobs/send_welcome_email.rs` — `SendWelcomeEmailArgs` struct and a
//!   `#[job]` handler with a commented enqueue snippet and an inline smoke test.
//! - `src/jobs/mod.rs` — created or updated with `pub mod send_welcome_email;`
//!   and an idempotent `registered_jobs()` aggregator.
//! - `src/main.rs` — `mod jobs;` declaration and
//!   `.jobs(jobs::registered_jobs())` wired into the app builder chain.

use std::path::Path;

use super::dsl::{Field, parse_fields};
use super::emit::Plan;
use super::model::validate_resource_name;
use super::naming::{pascal, snake};
use super::schema_edit::{
    add_jobs_registration_to_app, add_mod_declaration, augment_registered_jobs, update_main_rs,
};
use super::{Flags, GenerateError, ensure_project_root, read_or_empty};

/// Extra Cargo dependencies the job generator's output requires.
const JOB_DEPS: &[(&str, &str)] = &[("serde", "{ version = \"1\", features = [\"derive\"] }")];

/// Compute the file actions for `autumn generate job`.
///
/// # Errors
/// Returns errors for project-layout issues and name-validation failures.
pub fn plan_job(project_root: &Path, name: &str, fields: &[String]) -> Result<Plan, GenerateError> {
    ensure_project_root(project_root)?;
    validate_resource_name(name)?;

    let parsed_fields = parse_fields(fields)?;
    let snake_name = snake(name);
    let pascal_name = pascal(name);
    let args_struct = format!("{pascal_name}Args");
    let companion_struct = format!("{pascal_name}Job");
    let job_entry = format!("{snake_name}::{snake_name}");

    let mut plan = Plan::new(project_root);

    // ── src/jobs/<snake>.rs ───────────────────────────────────────────────
    plan.create(
        project_root
            .join("src")
            .join("jobs")
            .join(format!("{snake_name}.rs")),
        render_job_file(&snake_name, &args_struct, &companion_struct, &parsed_fields),
    );

    // ── src/jobs/mod.rs (create or update) ────────────────────────────────
    let mod_path = project_root.join("src").join("jobs").join("mod.rs");
    let existing_mod = read_or_empty(&mod_path);
    let with_mod_decl = add_mod_declaration(&existing_mod, &snake_name);
    let with_aggregator = augment_registered_jobs(&with_mod_decl, &job_entry);
    plan.modify(mod_path, with_aggregator);

    // ── src/main.rs: add mod jobs; and .jobs(…) ───────────────────────────
    let main_path = project_root.join("src").join("main.rs");
    let main_existing = std::fs::read_to_string(&main_path).map_err(|e| {
        GenerateError::Io(std::io::Error::new(
            e.kind(),
            format!("{}: {e}", main_path.display()),
        ))
    })?;
    let with_mod = update_main_rs(&main_existing, &["jobs"], &[]);
    let updated_main = add_jobs_registration_to_app(&with_mod);
    plan.modify(main_path, updated_main);

    // ── Cargo.toml: ensure serde dep ──────────────────────────────────────
    super::model::plan_cargo_deps(&mut plan, project_root, JOB_DEPS);

    Ok(plan)
}

/// Render `src/jobs/<snake>.rs`.
fn render_job_file(
    snake_name: &str,
    args_struct: &str,
    companion_struct: &str,
    fields: &[Field],
) -> String {
    let fields_block = render_fields(fields);
    let smoke_test = render_smoke_test(snake_name, companion_struct);
    format!(
        r#"//! Generated by `autumn generate job`.
//!
//! Edit freely — once generated, this is ordinary user code.
//!
//! The `#[job]` macro generates a companion struct `{companion_struct}` with:
//!   - `{companion_struct}::NAME: &'static str` — the registered job name.
//!   - `{companion_struct}::enqueue(args).await?` — at-least-once enqueue.
//!   - `{companion_struct}::enqueue_in(delay, args).await?` — delayed enqueue.
//!   - `{companion_struct}::enqueue_at(time, args).await?` — scheduled enqueue.
//!
//! To enqueue from a handler, pick one of:
//!
//!     // At-least-once (idempotency burden is yours):
//!     {companion_struct}::enqueue(args).await?;
//!
//!     // Transactional — enqueues only if the surrounding DB transaction commits:
//!     autumn_web::job::enqueue_on_conn({companion_struct}::NAME, &args, conn).await?;

use autumn_web::prelude::*;
use serde::{{Deserialize, Serialize}};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct {args_struct} {{{fields_block}}}

#[job(name = "{snake_name}", max_attempts = 5, backoff_ms = 500)]
pub async fn {snake_name}(_state: AppState, _args: {args_struct}) -> AutumnResult<()> {{
    // TODO: implement job body here.
    Ok(())
}}
{smoke_test}"#
    )
}

/// Render the fields block for the args struct.
fn render_fields(fields: &[Field]) -> String {
    use std::fmt::Write as _;
    if fields.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    for f in fields {
        write!(out, "\n    pub {}: {},", f.name, f.rust_type()).unwrap();
    }
    out.push('\n');
    out
}

/// Render the inline smoke test.
fn render_smoke_test(snake_name: &str, companion_struct: &str) -> String {
    format!(
        r#"
#[cfg(test)]
mod {snake_name}_job_tests {{
    use super::*;

    #[test]
    fn {snake_name}_job_name_matches_handler() {{
        assert_eq!({companion_struct}::NAME, "{snake_name}");
    }}
}}
"#
    )
}

/// CLI entry point.
pub fn run(name: &str, fields: &[String], flags: Flags) {
    let cwd = match std::env::current_dir() {
        Ok(d) => d,
        Err(e) => {
            eprintln!("Error: cannot determine current directory: {e}");
            std::process::exit(1);
        }
    };
    match plan_job(&cwd, name, fields).and_then(|p| p.execute(flags)) {
        Ok(()) => {}
        Err(e) => {
            eprintln!("Error: {e}");
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn project_with_main(main_content: &str) -> TempDir {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join("Cargo.toml"),
            "[package]\nname=\"x\"\n\n[dependencies]\nautumn-web = \"0.6\"\n",
        )
        .unwrap();
        fs::create_dir_all(tmp.path().join("src")).unwrap();
        fs::write(tmp.path().join("src/main.rs"), main_content).unwrap();
        tmp
    }

    fn default_main() -> &'static str {
        r#"use autumn_web::prelude::*;

#[get("/")]
async fn index() -> &'static str { "ok" }

#[autumn_web::main]
async fn main() {
    autumn_web::app()
        .routes(routes![index])
        .run()
        .await;
}
"#
    }

    // ── RED: plan assertions ─────────────────────────────────────────────

    #[test]
    fn plan_creates_job_file() {
        let tmp = project_with_main(default_main());
        let plan = plan_job(tmp.path(), "SendWelcomeEmail", &[]).unwrap();
        assert!(
            plan.actions
                .iter()
                .any(|a| a.path().ends_with("src/jobs/send_welcome_email.rs")),
            "plan must include src/jobs/send_welcome_email.rs"
        );
    }

    #[test]
    fn plan_includes_jobs_mod_rs() {
        let tmp = project_with_main(default_main());
        let plan = plan_job(tmp.path(), "SendWelcomeEmail", &[]).unwrap();
        assert!(
            plan.actions
                .iter()
                .any(|a| a.path().ends_with("src/jobs/mod.rs")),
            "plan must include src/jobs/mod.rs"
        );
    }

    #[test]
    fn plan_modifies_main_rs() {
        let tmp = project_with_main(default_main());
        let plan = plan_job(tmp.path(), "SendWelcomeEmail", &[]).unwrap();
        assert!(
            plan.actions
                .iter()
                .any(|a| a.path().ends_with("src/main.rs")),
            "plan must modify src/main.rs"
        );
    }

    #[test]
    fn plan_errors_when_not_in_project() {
        let tmp = TempDir::new().unwrap();
        let err = plan_job(tmp.path(), "SendWelcomeEmail", &[]).unwrap_err();
        assert!(matches!(err, GenerateError::NotInProject));
    }

    #[test]
    fn plan_errors_when_main_rs_missing() {
        let tmp = TempDir::new().unwrap();
        fs::write(tmp.path().join("Cargo.toml"), "[package]\nname=\"x\"\n").unwrap();
        let err = plan_job(tmp.path(), "SendWelcomeEmail", &[]).unwrap_err();
        assert!(matches!(err, GenerateError::Io(_)));
    }

    #[test]
    fn plan_rejects_invalid_name() {
        let tmp = project_with_main(default_main());
        let err = plan_job(tmp.path(), "123invalid", &[]).unwrap_err();
        assert!(
            matches!(err, GenerateError::InvalidName(_, _)),
            "must reject numeric-prefix name"
        );
    }

    // ── GREEN: execute and inspect written content ───────────────────────

    #[test]
    fn execute_writes_args_struct_with_correct_derives() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &["user_id:i64".to_string()])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(
            src.contains("pub struct SendWelcomeEmailArgs"),
            "must define args struct"
        );
        assert!(
            src.contains("pub user_id: i64"),
            "must include parsed field"
        );
        assert!(
            src.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"),
            "args struct must derive Serialize + Deserialize"
        );
    }

    #[test]
    fn execute_writes_job_handler_with_correct_attribute() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(
            src.contains(
                r#"#[job(name = "send_welcome_email", max_attempts = 5, backoff_ms = 500)]"#
            ),
            "#[job] attribute must be present: {src}"
        );
        assert!(
            src.contains("pub async fn send_welcome_email("),
            "handler fn must be pub async: {src}"
        );
    }

    #[test]
    fn execute_writes_enqueue_snippet() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(
            src.contains("SendWelcomeEmailJob::enqueue"),
            "file must contain at-least-once enqueue snippet"
        );
        assert!(
            src.contains("enqueue_on_conn"),
            "file must contain transactional enqueue snippet"
        );
    }

    #[test]
    fn execute_writes_inline_smoke_test_with_name_assertion() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(
            src.contains("#[cfg(test)]"),
            "must include an inline test module"
        );
        assert!(
            src.contains("SendWelcomeEmailJob::NAME"),
            "smoke test must assert the NAME constant"
        );
        assert!(
            src.contains(r#""send_welcome_email""#),
            "smoke test must check the string value of NAME"
        );
    }

    #[test]
    fn execute_writes_mod_rs_with_pub_mod_and_aggregator() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let mod_rs = fs::read_to_string(tmp.path().join("src/jobs/mod.rs")).unwrap();
        assert!(
            mod_rs.contains("pub mod send_welcome_email;"),
            "must declare pub mod"
        );
        assert!(
            mod_rs.contains("pub fn registered_jobs()"),
            "must define registered_jobs fn"
        );
        assert!(
            mod_rs.contains("jobs![send_welcome_email::send_welcome_email]"),
            "registered_jobs must list the new job"
        );
    }

    #[test]
    fn execute_updates_main_rs_with_mod_declaration() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let main = fs::read_to_string(tmp.path().join("src/main.rs")).unwrap();
        assert!(main.contains("mod jobs;"), "main.rs must declare mod jobs");
    }

    #[test]
    fn execute_updates_main_rs_with_jobs_call() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let main = fs::read_to_string(tmp.path().join("src/main.rs")).unwrap();
        assert!(
            main.contains(".jobs(jobs::registered_jobs())"),
            "main.rs must include .jobs() call: {main}"
        );
        let jobs_pos = main.find(".jobs(").unwrap();
        let run_pos = main.find(".run()").unwrap();
        assert!(jobs_pos < run_pos, ".jobs() must precede .run()");
    }

    // ── Name normalisation ────────────────────────────────────────────────

    #[test]
    fn snake_case_input_is_normalised() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "send_welcome_email", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        assert!(tmp.path().join("src/jobs/send_welcome_email.rs").exists());
        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(src.contains("SendWelcomeEmailArgs"));
        assert!(src.contains("SendWelcomeEmailJob"));
    }

    #[test]
    fn pascal_case_input_is_normalised() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        assert!(tmp.path().join("src/jobs/send_welcome_email.rs").exists());
    }

    // ── Field rendering ───────────────────────────────────────────────────

    #[test]
    fn multiple_fields_all_rendered_in_args_struct() {
        let tmp = project_with_main(default_main());
        plan_job(
            tmp.path(),
            "PostNotification",
            &[
                "post_id:i64".to_string(),
                "title:String".to_string(),
                "published:bool".to_string(),
            ],
        )
        .unwrap()
        .execute(Flags::default())
        .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/post_notification.rs")).unwrap();
        assert!(src.contains("pub post_id: i64"));
        assert!(src.contains("pub title: String"));
        assert!(src.contains("pub published: bool"));
    }

    #[test]
    fn optional_field_is_rendered_as_option() {
        let tmp = project_with_main(default_main());
        plan_job(
            tmp.path(),
            "SendEmail",
            &["reply_to:Option<String>".to_string()],
        )
        .unwrap()
        .execute(Flags::default())
        .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_email.rs")).unwrap();
        assert!(src.contains("pub reply_to: Option<String>"));
    }

    // ── Flag behaviour ────────────────────────────────────────────────────

    #[test]
    fn dry_run_writes_no_new_files() {
        let tmp = project_with_main(default_main());
        let original_main = fs::read_to_string(tmp.path().join("src/main.rs")).unwrap();
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags {
                dry_run: true,
                force: false,
            })
            .unwrap();

        assert!(
            !tmp.path().join("src/jobs/send_welcome_email.rs").exists(),
            "dry run must not write the job file"
        );
        assert!(
            !tmp.path().join("src/jobs/mod.rs").exists(),
            "dry run must not write mod.rs"
        );
        let main_after = fs::read_to_string(tmp.path().join("src/main.rs")).unwrap();
        assert_eq!(original_main, main_after, "dry run must not modify main.rs");
    }

    #[test]
    fn collision_without_force_returns_error() {
        let tmp = project_with_main(default_main());
        fs::create_dir_all(tmp.path().join("src/jobs")).unwrap();
        fs::write(
            tmp.path().join("src/jobs/send_welcome_email.rs"),
            "// existing",
        )
        .unwrap();
        let err = plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap_err();
        assert!(
            matches!(err, GenerateError::Collisions(_)),
            "should return collision error; got {err:?}"
        );
    }

    #[test]
    fn force_overwrites_existing_job() {
        let tmp = project_with_main(default_main());
        fs::create_dir_all(tmp.path().join("src/jobs")).unwrap();
        fs::write(tmp.path().join("src/jobs/send_welcome_email.rs"), "// old").unwrap();
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags {
                force: true,
                dry_run: false,
            })
            .unwrap();

        let src = fs::read_to_string(tmp.path().join("src/jobs/send_welcome_email.rs")).unwrap();
        assert!(
            src.contains("SendWelcomeEmailArgs"),
            "force must regenerate the job file"
        );
    }

    // ── Idempotency: second job augments but doesn't duplicate ─────────────

    #[test]
    fn second_job_augments_mod_rs_without_duplication() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();
        plan_job(tmp.path(), "PostNotification", &["post_id:i64".to_string()])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let mod_rs = fs::read_to_string(tmp.path().join("src/jobs/mod.rs")).unwrap();
        assert!(mod_rs.contains("pub mod send_welcome_email;"));
        assert!(mod_rs.contains("pub mod post_notification;"));
        assert!(mod_rs.contains("send_welcome_email::send_welcome_email"));
        assert!(mod_rs.contains("post_notification::post_notification"));
        assert_eq!(
            mod_rs.matches("pub fn registered_jobs").count(),
            1,
            "registered_jobs must appear exactly once"
        );
    }

    #[test]
    fn second_job_does_not_duplicate_jobs_call_in_main() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();
        plan_job(tmp.path(), "PostNotification", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let main = fs::read_to_string(tmp.path().join("src/main.rs")).unwrap();
        assert_eq!(
            main.matches(".jobs(jobs::registered_jobs())").count(),
            1,
            ".jobs() must appear exactly once in main.rs"
        );
        assert_eq!(
            main.matches("mod jobs;").count(),
            1,
            "mod jobs; must appear exactly once in main.rs"
        );
    }

    #[test]
    fn rerunning_same_job_is_idempotent_for_mod_rs() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();
        // Second run with --force (job file already exists)
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags {
                force: true,
                dry_run: false,
            })
            .unwrap();

        let mod_rs = fs::read_to_string(tmp.path().join("src/jobs/mod.rs")).unwrap();
        assert_eq!(
            mod_rs.matches("pub mod send_welcome_email;").count(),
            1,
            "pub mod must appear exactly once"
        );
        assert_eq!(
            mod_rs
                .matches("send_welcome_email::send_welcome_email")
                .count(),
            1,
            "jobs entry must appear exactly once"
        );
    }

    // ── Cargo.toml ────────────────────────────────────────────────────────

    #[test]
    fn execute_adds_serde_to_cargo_toml() {
        let tmp = project_with_main(default_main());
        plan_job(tmp.path(), "SendWelcomeEmail", &[])
            .unwrap()
            .execute(Flags::default())
            .unwrap();

        let cargo = fs::read_to_string(tmp.path().join("Cargo.toml")).unwrap();
        assert!(
            cargo.contains("serde"),
            "Cargo.toml must include serde: {cargo}"
        );
    }
}
