//! The JSON REST / MCP surface generated by `#[repository(..., api = "/path")]`.
//!
//! This is not data access. It emits `axum` handlers, their route-info
//! registrations, the `OpenAPI` schemas they document and the MCP tool
//! projection — roughly 1,100 lines of template that a repository with no
//! `api` key never uses. It lives here so `repository_macro` describes the
//! database surface and this module describes the HTTP one.
//!
//! The seam is narrow on purpose: [`ApiInputs`] is the whole of what the
//! caller must hand over, and everything else is derived from [`RepoConfig`].

// Every item here is crate-internal by design: this crate exports nothing but
// its proc-macro entry points, so `pub(crate)` can never widen to anything
// callers see. It is kept over `pub` to say so (clippy::redundant_pub_crate).
#![allow(clippy::redundant_pub_crate)]

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::Ident;

use crate::repository::{McpExpose, RepoConfig, to_snake_case};

/// What `repository_macro` must hand to the API emitter.
///
/// Every other value the handlers need is computed here or read from
/// [`RepoConfig`].
pub(crate) struct ApiInputs<'a> {
    /// The model type the routes read and write.
    pub model_name: &'a Ident,
    /// The `New{Model}` insert type a create route decodes.
    pub new_name: &'a Ident,
    /// The `Update{Model}` patch type an update route decodes.
    pub update_name: &'a Ident,
    /// The generated `Pg{Trait}` repository the handlers extract.
    pub pg_name: &'a Ident,
    /// Commit-hook route registration, spliced into each handler that writes.
    pub route_hook_registration: &'a TokenStream,
    /// The declared trait's visibility, which the handlers inherit.
    pub vis: &'a syn::Visibility,
}

/// Emit the API handlers, or nothing when the repository declares no `api`.
// The same grandfathered allows `repository_macro` carries: this body was
// lifted out of it verbatim, so the lint surface moved with the code.
#[allow(
    clippy::too_many_lines,
    clippy::option_if_let_else,
    clippy::large_stack_frames,
    clippy::cognitive_complexity
)]
pub(crate) fn emit_api_handlers(config: &RepoConfig, inputs: &ApiInputs<'_>) -> TokenStream {
    let ApiInputs {
        model_name,
        new_name,
        update_name,
        pg_name,
        route_hook_registration,
        vis,
    } = inputs;

    let Some(ref api_path) = config.api_path else {
        return quote! {};
    };

    let prefix = to_snake_case(&model_name.to_string());

    // #1654: the generated CRUD handlers return the model through `Json`.
    // If the model carries a `#[classified]` column it is not `JsonSink`, so
    // the handlers cannot compile -- but the failure surfaces as axum's
    // `Handler` bound, which swallows autumn's own diagnostic. Assert the
    // obligation directly first so the developer reads the message that says
    // what is wrong and what to do. This is a call-site obligation, not a
    // trivial where-clause, so it costs nothing for an unclassified model.
    let api_sink_assertion = quote! {
        const _: () = {
            fn __autumn_api_response_must_be_releasable<
                __T: ::autumn_web::classify::JsonSink,
            >() {
            }
            #[allow(dead_code)]
            fn __autumn_assert_api_response_is_releasable() {
                __autumn_api_response_must_be_releasable::<#model_name>();
            }
        };
    };

    let list_fn = format_ident!("{prefix}_api_list");
    let get_fn = format_ident!("{prefix}_api_get");
    let create_fn = format_ident!("{prefix}_api_create");
    let update_fn = format_ident!("{prefix}_api_update");
    let delete_fn = format_ident!("{prefix}_api_delete");

    let list_info = format_ident!("__autumn_route_info_{prefix}_api_list");
    let get_info = format_ident!("__autumn_route_info_{prefix}_api_get");
    let create_info = format_ident!("__autumn_route_info_{prefix}_api_create");
    let update_info = format_ident!("__autumn_route_info_{prefix}_api_update");
    let delete_info = format_ident!("__autumn_route_info_{prefix}_api_delete");

    let list_path_fn = format_ident!("__autumn_path_{prefix}_api_list");
    let get_path_fn = format_ident!("__autumn_path_{prefix}_api_get");
    let create_path_fn = format_ident!("__autumn_path_{prefix}_api_create");
    let update_path_fn = format_ident!("__autumn_path_{prefix}_api_update");
    let delete_path_fn = format_ident!("__autumn_path_{prefix}_api_delete");

    let id_path = format!("{api_path}/{{id}}");

    // MCP opt-in classified by each generated route's verb (mirroring the
    // runtime read-only rule), not hand-placed per site — a future
    // generated route picks up the right classification from the same
    // `method:` literal it declares.
    let mcp_for = |method: &str| match config.mcp_expose {
        None => false,
        Some(McpExpose::Read) => matches!(method, "GET" | "HEAD"),
        Some(McpExpose::All) => true,
    };
    let mcp_list_op = mcp_for("GET");
    let mcp_get_op = mcp_for("GET");
    let mcp_create_op = mcp_for("POST");
    let mcp_update_op = mcp_for("PUT");
    let mcp_delete_op = mcp_for("DELETE");

    let has_policy = config.policy_type.is_some();

    // #1237: the generated JSON list endpoint paginates by default instead
    // of streaming the whole table via `find_all()`. Offset pagination
    // (`?page`/`?size` → `Page`) is the default; declaring `cursor_key`
    // opts the endpoint into keyset/cursor mode (`?cursor`/`?size` →
    // `CursorPage`) for large/append-only tables. Cursor mode only replaces
    // the *plain* list path — a `scope`/`policy` list still paginates by
    // offset so its per-row authorization filter (which must run in Rust)
    // stays correct.
    let use_cursor = config.cursor_key.is_some() && config.scope_type.is_none() && !has_policy;
    let list_return_type = if use_cursor {
        quote! { ::autumn_web::pagination::CursorPage<#model_name> }
    } else {
        quote! { ::autumn_web::pagination::Page<#model_name> }
    };
    let list_pager_arg = if use_cursor {
        quote! { __autumn_cursor_req: ::autumn_web::pagination::CursorRequest, }
    } else {
        quote! { __autumn_page_req: ::autumn_web::pagination::PageRequest, }
    };

    let policy_check_show = if has_policy {
        quote! {
            ::autumn_web::authorization::__check_policy_scoped::<#model_name>(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                "show",
                &record,
            )
            .await?;
        }
    } else {
        quote! {}
    };
    // POST endpoint runs `can_create` *before* the insert so a
    // denied check never commits a row. Naive after-the-fact
    // policy checks would write the row, then return 403/404,
    // leaving the data behind.
    let policy_check_create_pre = if has_policy {
        quote! {
            ::autumn_web::authorization::__check_policy_create_payload_scoped::<#model_name>(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                &__autumn_new_payload,
            )
            .await?;
        }
    } else {
        quote! {}
    };
    // Policy-backed create handlers keep the raw JSON value for
    // `can_create_payload` instead of serializing `NewModel` back
    // into JSON. That preserves hand-written `NewModel` types that
    // are `Deserialize + Insertable` but intentionally not `Serialize`.
    let create_payload_arg = if has_policy {
        quote! {
            ::autumn_web::prelude::Json(__autumn_new_payload): ::autumn_web::prelude::Json<
                ::autumn_web::reexports::serde_json::Value
            >
        }
    } else {
        quote! {
            ::autumn_web::prelude::Json(new): ::autumn_web::prelude::Json<#new_name>
        }
    };
    let decode_create_payload = if has_policy {
        quote! {
            let new: #new_name = ::autumn_web::reexports::serde_json::from_value(
                __autumn_new_payload.clone(),
            )
            .map_err(|err| ::autumn_web::AutumnError::unprocessable_msg(err.to_string()))?;
        }
    } else {
        quote! {}
    };
    let policy_check_update_pre = if has_policy {
        quote! {
            let __existing = repo.on_primary().find_by_id(id).await?
                .ok_or_else(|| ::autumn_web::AutumnError::not_found_msg("not found"))?;
            ::autumn_web::authorization::__check_policy_scoped::<#model_name>(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                "update",
                &__existing,
            )
            .await?;
        }
    } else {
        quote! {}
    };
    let policy_check_delete_pre = if has_policy {
        quote! {
            let __existing = repo.on_primary().find_by_id(id).await?
                .ok_or_else(|| ::autumn_web::AutumnError::not_found_msg("not found"))?;
            ::autumn_web::authorization::__check_policy_scoped::<#model_name>(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                "delete",
                &__existing,
            )
            .await?;
        }
    } else {
        quote! {}
    };
    let session_state_args = if has_policy {
        quote! {
            ::autumn_web::reexports::axum::extract::State(__autumn_state):
                ::autumn_web::reexports::axum::extract::State<::autumn_web::AppState>,
            __autumn_session: ::autumn_web::session::Session,
            __autumn_token_scopes: ::core::option::Option<
                ::autumn_web::reexports::axum::extract::Extension<
                    ::autumn_web::auth::ApiTokenScopes
                >
            >,
            __autumn_idempotency_replay: ::core::option::Option<
                ::autumn_web::reexports::axum::extract::Extension<
                    ::autumn_web::idempotency::IdempotencyReplayResponse
                >
            >,
        }
    } else {
        quote! {}
    };
    // List endpoint behavior, in order of precedence:
    //
    // 1. `scope = SomeScope`: invoke the registered scope. The most efficient
    //    form — the scope filters at the SQL level via Diesel.
    // 2. `policy = SomePolicy` without `scope`: load every record, then filter
    //    through `Policy::can_show` per row. Slower than (1) on large tables,
    //    but it closes the "policy guards show/update/delete but list returns
    //    everything" exposure path. Set `scope = SomeScope` too if performance
    //    matters.
    // 3. Neither: plain `repo.find_all()`, a public list.
    let scope_list_body = if config.scope_type.is_some() {
        // Scope filters at the SQL level, but the filtered set is still
        // returned in full — window it in memory so the response stays
        // bounded and carries the `Page` envelope + `Link` headers.
        quote! {
            let __scope = __autumn_state
                .scope::<#model_name>()
                .ok_or_else(|| ::autumn_web::AutumnError::internal_server_error_msg(
                    "missing scope registration"
                ))?;
            let __ctx = ::autumn_web::authorization::PolicyContext::from_request_parts(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
            ).await;
            let mut __conn = repo.__autumn_acquire_read_conn().await?;
            let records = __scope.list(&__ctx, &mut __conn).await?;
            Ok(::autumn_web::pagination::Page::paginate_in_memory(records, &__autumn_page_req))
        }
    } else if has_policy {
        // Per-row policy checks must run in Rust, so every candidate row is
        // loaded and filtered before the page window is applied. The
        // response is still bounded to one page and self-describing.
        quote! {
            let __policy = __autumn_state
                .policy::<#model_name>()
                .ok_or_else(|| ::autumn_web::AutumnError::internal_server_error_msg(
                    "missing policy registration"
                ))?;
            let __ctx = ::autumn_web::authorization::PolicyContext::from_request_parts(
                &__autumn_state,
                &__autumn_session,
                __autumn_token_scopes.as_ref().map(|__e| &__e.0),
            ).await;
            let __all = repo.find_all().await?;
            let mut __filtered = ::std::vec::Vec::with_capacity(__all.len());
            for __record in __all {
                if __policy.can_show(&__ctx, &__record).await {
                    __filtered.push(__record);
                }
            }
            Ok(::autumn_web::pagination::Page::paginate_in_memory(__filtered, &__autumn_page_req))
        }
    } else if use_cursor {
        // Keyset/cursor mode (opted in via `cursor_key`): reuse the
        // generated `cursor_page()` for O(1) page depth on append-only
        // tables. Emits a cursor `Link: rel="next"`.
        quote! {
            repo.cursor_page(&__autumn_cursor_req).await
        }
    } else {
        // Default: offset pagination via the generated `page()` — a single
        // bounded `LIMIT/OFFSET` + `COUNT(*)`, never `find_all()`.
        quote! {
            repo.page(&__autumn_page_req).await
        }
    };
    // Inject session + state extractors when *either* a scope
    // or a policy is configured ΓÇö both code paths above need
    // them.
    let list_session_state_args = if config.scope_type.is_some() || has_policy {
        quote! {
            ::autumn_web::reexports::axum::extract::State(__autumn_state):
                ::autumn_web::reexports::axum::extract::State<::autumn_web::AppState>,
            __autumn_session: ::autumn_web::session::Session,
            __autumn_token_scopes: ::core::option::Option<
                ::autumn_web::reexports::axum::extract::Extension<
                    ::autumn_web::auth::ApiTokenScopes
                >
            >,
        }
    } else {
        quote! {}
    };
    let resource_type_name_lit = model_name.to_string();
    let api_path_lit = api_path.clone();

    // #1237: OpenAPI for the paginated list operation — document the
    // `page`/`size` (or `cursor`/`size`) query params and the `Page`
    // (or `CursorPage`) response envelope, replacing the old bare array.
    let list_schema_fn = format_ident!("__autumn_openapi_schemas_{prefix}_api_list");
    let list_query_schema_name = if use_cursor {
        "CursorRequest"
    } else {
        "PageRequest"
    };
    let list_response_schema_name = if use_cursor {
        format!("{model_name}CursorPage")
    } else {
        format!("{model_name}Page")
    };
    let model_component_ref = format!("#/components/schemas/{model_name}");
    // Runtime-inserted component schemas: the pagination request query
    // object and the response envelope wrapping an array of the model.
    let list_query_schema_json = if use_cursor {
        quote! {
            ::autumn_web::reexports::serde_json::json!({
                "type": "object",
                "properties": {
                    "cursor": { "type": "string", "description": "Opaque keyset cursor for the next page" },
                    "size": { "type": "integer", "minimum": 1, "maximum": 100, "default": 20 }
                }
            })
        }
    } else {
        quote! {
            ::autumn_web::reexports::serde_json::json!({
                "type": "object",
                "properties": {
                    "page": { "type": "integer", "minimum": 1, "default": 1 },
                    "size": { "type": "integer", "minimum": 1, "maximum": 100, "default": 20 }
                }
            })
        }
    };
    let list_response_schema_json = if use_cursor {
        quote! {
            ::autumn_web::reexports::serde_json::json!({
                "type": "object",
                "required": ["content", "size", "has_next"],
                "properties": {
                    "content": { "type": "array", "items": { "$ref": #model_component_ref } },
                    "size": { "type": "integer" },
                    "next_cursor": { "type": ["string", "null"] },
                    "has_next": { "type": "boolean" }
                }
            })
        }
    } else {
        quote! {
            ::autumn_web::reexports::serde_json::json!({
                "type": "object",
                "required": ["content", "page", "size", "total_elements", "total_pages", "has_next", "has_previous"],
                "properties": {
                    "content": { "type": "array", "items": { "$ref": #model_component_ref } },
                    "page": { "type": "integer" },
                    "size": { "type": "integer" },
                    "total_elements": { "type": "integer" },
                    "total_pages": { "type": "integer" },
                    "has_next": { "type": "boolean" },
                    "has_previous": { "type": "boolean" }
                }
            })
        }
    };
    let list_schema_registration = quote! {
        #[doc(hidden)]
        #vis fn #list_schema_fn(
            __autumn_reg: &mut ::autumn_web::openapi::SchemaRegistry,
        ) {
            __autumn_reg.insert(#list_query_schema_name, #list_query_schema_json);
            __autumn_reg.insert(#list_response_schema_name, #list_response_schema_json);
        }
    };

    // Compile-time assertion: when the user writes
    // `policy = SomePolicy`, the generated code references the
    // type so a typo (or a real type that doesn't `impl
    // Policy<Model>`) fails compilation here, not at the first
    // request with `500 missing policy registration`.
    let policy_type_assertion = if let Some(ref policy_type) = config.policy_type {
        quote! {
            const _: fn() = || {
                fn __autumn_assert_policy<P: ::autumn_web::authorization::Policy<#model_name>>() {}
                __autumn_assert_policy::<#policy_type>();
            };
        }
    } else {
        quote! {}
    };
    // Emit a type-erased registry probe so the app builder can
    // verify at startup that the policy was actually registered
    // via `.policy::<R, _>(...)`. Without this, forgetting the
    // `.policy(...)` call would compile and boot, then 500 on
    // every protected request.
    let policy_check_fn = if config.policy_type.is_some() {
        quote! {
            ::core::option::Option::Some(
                (|registry: &::autumn_web::authorization::PolicyRegistry| {
                    registry.has_policy::<#model_name>()
                }) as fn(&::autumn_web::authorization::PolicyRegistry) -> bool
            )
        }
    } else {
        quote! { ::core::option::Option::None }
    };
    // Companion probe for `scope = ...`, attached only to the `_api_list`
    // route's metadata. The other auto-generated routes (`*_api_get`,
    // `*_api_create`, `*_api_update`, `*_api_delete`) never call `scope.list`,
    // so flagging them for missing scope registration would fire the prod
    // fail-fast even when the user deliberately mounted only non-list endpoints
    // with `scope = ...` configured — reads happen via custom queries, but the
    // scope is still declared so `Note::scope(&ctx)` works in hand-written list
    // handlers. The non-list routes get `scope_check: None` regardless.
    let list_scope_check_fn = if config.scope_type.is_some() {
        quote! {
            ::core::option::Option::Some(
                (|registry: &::autumn_web::authorization::PolicyRegistry| {
                    registry.scope::<#model_name>().is_some()
                }) as fn(&::autumn_web::authorization::PolicyRegistry) -> bool
            )
        }
    } else {
        quote! { ::core::option::Option::None }
    };
    let non_list_scope_check_fn = quote! { ::core::option::Option::None };
    let scope_type_assertion = if let Some(ref scope_type) = config.scope_type {
        quote! {
            const _: fn() = || {
                fn __autumn_assert_scope<S: ::autumn_web::authorization::Scope<#model_name>>() {}
                __autumn_assert_scope::<#scope_type>();
            };
        }
    } else {
        quote! {}
    };

    // #1253: run the model's `#[validate(...)]` rules on the decoded write
    // payload before it reaches the DB, returning a 422 Problem Details with the
    // per-field `errors` map on failure. Autoref specialization (`MaybeValidate`)
    // makes a payload type that does not implement `validator::Validate` — a
    // `NewModel` with no `#[validate]` fields, or a hand-written insert type —
    // compile to a no-op, so existing repositories need no migration.
    //
    // `?`-flavoured for the plain `AutumnResult` handlers. The policy-backed
    // handlers return `IdempotencyReplayOr`, so they get an explicit early return
    // that wraps the error in `Inner`.
    let validate_new = quote! {
        {
            // Both traits must be in scope for autoref resolution to
            // choose between them; exactly one is used for any concrete
            // payload type, so the other is (correctly) unused.
            #[allow(unused_imports)]
            use ::autumn_web::validation::{
                MaybeValidateFallback as _, MaybeValidateViaValidator as _,
            };
            (&::autumn_web::validation::MaybeValidate(&new)).autumn_maybe_validate()?;
        }
    };
    let validate_patch = quote! {
        {
            // Both traits must be in scope for autoref resolution to
            // choose between them; exactly one is used for any concrete
            // payload type, so the other is (correctly) unused.
            #[allow(unused_imports)]
            use ::autumn_web::validation::{
                MaybeValidateFallback as _, MaybeValidateViaValidator as _,
            };
            (&::autumn_web::validation::MaybeValidate(&patch)).autumn_maybe_validate()?;
        }
    };
    let validate_new_idempotency = quote! {
        {
            // Both traits must be in scope for autoref resolution to
            // choose between them; exactly one is used for any concrete
            // payload type, so the other is (correctly) unused.
            #[allow(unused_imports)]
            use ::autumn_web::validation::{
                MaybeValidateFallback as _, MaybeValidateViaValidator as _,
            };
            if let ::core::result::Result::Err(err) =
                (&::autumn_web::validation::MaybeValidate(&new)).autumn_maybe_validate()
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
        }
    };
    let validate_patch_idempotency = quote! {
        {
            // Both traits must be in scope for autoref resolution to
            // choose between them; exactly one is used for any concrete
            // payload type, so the other is (correctly) unused.
            #[allow(unused_imports)]
            use ::autumn_web::validation::{
                MaybeValidateFallback as _, MaybeValidateViaValidator as _,
            };
            if let ::core::result::Result::Err(err) =
                (&::autumn_web::validation::MaybeValidate(&patch)).autumn_maybe_validate()
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
        }
    };

    let create_return_type = if has_policy {
        quote! {
            ::autumn_web::idempotency::IdempotencyReplayOr<
                ::autumn_web::AutumnResult<(
                    ::autumn_web::reexports::http::StatusCode,
                    ::autumn_web::prelude::Json<#model_name>
                )>
            >
        }
    } else {
        quote! {
            ::autumn_web::AutumnResult<(
                ::autumn_web::reexports::http::StatusCode,
                ::autumn_web::prelude::Json<#model_name>
            )>
        }
    };
    let create_body = if has_policy {
        quote! {
            let new: #new_name = match ::autumn_web::reexports::serde_json::from_value(
                __autumn_new_payload.clone(),
            ) {
                ::core::result::Result::Ok(new) => new,
                ::core::result::Result::Err(err) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(
                            ::autumn_web::AutumnError::unprocessable_msg(err.to_string())
                        )
                    );
                }
            };
            #validate_new_idempotency
            if let ::core::result::Result::Err(err) =
                ::autumn_web::authorization::__check_policy_create_payload_scoped::<#model_name>(
                    &__autumn_state,
                    &__autumn_session,
                    __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                    &__autumn_new_payload,
                )
                .await
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
            if let ::core::option::Option::Some(response) =
                ::autumn_web::idempotency::__replay_response(&__autumn_idempotency_replay)
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Replay(response);
            }
            let record = match repo.save(&new).await {
                ::core::result::Result::Ok(record) => record,
                ::core::result::Result::Err(err) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(err)
                    );
                }
            };
            ::autumn_web::idempotency::IdempotencyReplayOr::Inner(::core::result::Result::Ok((
                ::autumn_web::reexports::http::StatusCode::CREATED,
                ::autumn_web::prelude::Json(record)
            )))
        }
    } else {
        quote! {
            #decode_create_payload
            #validate_new
            #policy_check_create_pre
            let record = repo.save(&new).await?;
            Ok((::autumn_web::reexports::http::StatusCode::CREATED, ::autumn_web::prelude::Json(record)))
        }
    };
    let update_return_type = if has_policy {
        quote! {
            ::autumn_web::idempotency::IdempotencyReplayOr<
                ::autumn_web::AutumnResult<::autumn_web::prelude::Json<#model_name>>
            >
        }
    } else {
        quote! {
            ::autumn_web::AutumnResult<::autumn_web::prelude::Json<#model_name>>
        }
    };
    let update_body = if has_policy {
        // #1801: merged-model validation via `from_patch` structurally needs
        // the `#[model]`-generated `<Model>DraftExt` trait (and `Model:
        // Clone`, required by `UpdateDraft`). Hand-written models opt out of
        // the generated DTO scaffolding with `no_upsert_trait` and supply
        // their own changeset, so they have no `DraftExt`; skip the merged
        // check for them (the patch-level `#validate_patch_idempotency` above
        // still runs). Regression: repository_policy_non_serialize_new.rs.
        let merged_validate = if config.no_upsert_trait {
            quote! {}
        } else {
            let draft_ext_trait = format_ident!("{}DraftExt", model_name);
            quote! {
                // #1801: also validate the effective merged model (existing row
                // plus patch), so the full validator set runs against concrete
                // values, matching the hooked-repo precedent (#1804). Runs after
                // the 404, 403, and patch-422 checks and reuses the already-loaded
                // `__existing`, so there is no extra query. Only the 422 side
                // effect is wanted, so the draft is discarded and the blind
                // `repo.update` below is unchanged. Wrapped rather than `?`
                // because this handler returns `IdempotencyReplayOr`, and it sits
                // with the other pure pre-replay checks so it cannot affect
                // idempotency replay semantics.
                //
                // Concurrency: this is point-in-time. It validates against the
                // `__existing` snapshot loaded for the 404/policy gate, not under
                // a row lock held through `repo.update`, so it is best-effort
                // under concurrent writes — the same deliberate trade-off as the
                // blind path above, given the zero-extra-query design.
                if let ::core::result::Result::Err(err) =
                    <::autumn_web::hooks::UpdateDraft<#model_name> as #draft_ext_trait>::from_patch(&__existing, &patch)
                {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(err)
                    );
                }
            }
        };
        quote! {
            let __existing = match repo.on_primary().find_by_id(id).await {
                ::core::result::Result::Ok(::core::option::Option::Some(existing)) => existing,
                ::core::result::Result::Ok(::core::option::Option::None) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(::autumn_web::AutumnError::not_found_msg("not found"))
                    );
                }
                ::core::result::Result::Err(err) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(err)
                    );
                }
            };
            if let ::core::result::Result::Err(err) =
                ::autumn_web::authorization::__check_policy_scoped::<#model_name>(
                    &__autumn_state,
                    &__autumn_session,
                    __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                    "update",
                    &__existing,
                )
                .await
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
            // #1719 follow-up (Codex P2): validate the patch only after the
            // existence load (404) and the `__check_policy_scoped` gate
            // (403), so a policy-gated PUT/PATCH with an invalid body still
            // reports missing/unauthorized before unprocessable. Validation
            // is a pure check on the already-decoded `patch` and, like the
            // policy gate above, sits before the pure `__replay_response`
            // read, so it cannot affect idempotency replay semantics.
            #validate_patch_idempotency
            #merged_validate
            if let ::core::option::Option::Some(response) =
                ::autumn_web::idempotency::__replay_response(&__autumn_idempotency_replay)
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Replay(response);
            }
            let record = match repo.update(id, &patch).await {
                ::core::result::Result::Ok(record) => record,
                ::core::result::Result::Err(err) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(err)
                    );
                }
            };
            ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                ::core::result::Result::Ok(::autumn_web::prelude::Json(record))
            )
        }
    } else {
        quote! {
            #validate_patch
            #policy_check_update_pre
            let record = repo.update(id, &patch).await?;
            Ok(::autumn_web::prelude::Json(record))
        }
    };
    let delete_return_type = if has_policy {
        quote! {
            ::autumn_web::idempotency::IdempotencyReplayOr<
                ::autumn_web::AutumnResult<::autumn_web::reexports::http::StatusCode>
            >
        }
    } else {
        quote! {
            ::autumn_web::AutumnResult<::autumn_web::reexports::http::StatusCode>
        }
    };
    let delete_body = if has_policy {
        quote! {
            let __autumn_replay_response =
                ::autumn_web::idempotency::__replay_response(&__autumn_idempotency_replay);
            let __autumn_replay_deleted_record =
                ::autumn_web::idempotency::__replay_metadata(
                    &__autumn_idempotency_replay,
                    "repository.delete.record",
                );
            let __existing = match repo.on_primary().find_by_id(id).await {
                ::core::result::Result::Ok(::core::option::Option::Some(existing)) => existing,
                ::core::result::Result::Ok(::core::option::Option::None) => {
                    if let ::core::option::Option::Some(bytes) = __autumn_replay_deleted_record {
                        match ::autumn_web::reexports::serde_json::from_slice::<#model_name>(&bytes) {
                            ::core::result::Result::Ok(existing) => existing,
                            ::core::result::Result::Err(err) => {
                                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                                    ::core::result::Result::Err(
                                        ::autumn_web::AutumnError::internal_server_error_msg(err.to_string())
                                    )
                                );
                            }
                        }
                    } else {
                        return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                            ::core::result::Result::Err(::autumn_web::AutumnError::not_found_msg("not found"))
                        );
                    }
                }
                ::core::result::Result::Err(err) => {
                    return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                        ::core::result::Result::Err(err)
                    );
                }
            };
            if let ::core::result::Result::Err(err) =
                ::autumn_web::authorization::__check_policy_scoped::<#model_name>(
                    &__autumn_state,
                    &__autumn_session,
                    __autumn_token_scopes.as_ref().map(|__e| &__e.0),
                    "delete",
                    &__existing,
                )
                .await
            {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
            if let ::core::option::Option::Some(response) = __autumn_replay_response {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Replay(response);
            }
            let __autumn_deleted_record_metadata =
                match ::autumn_web::reexports::serde_json::to_vec(&__existing) {
                    ::core::result::Result::Ok(bytes) => bytes,
                    ::core::result::Result::Err(err) => {
                        return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                            ::core::result::Result::Err(
                                ::autumn_web::AutumnError::internal_server_error_msg(err.to_string())
                            )
                        );
                    }
                };
            if let ::core::result::Result::Err(err) = repo.delete_by_id(id).await {
                return ::autumn_web::idempotency::IdempotencyReplayOr::Inner(
                    ::core::result::Result::Err(err)
                );
            }
            ::autumn_web::idempotency::IdempotencyReplayOr::InnerWithReplayMetadata(
                ::core::result::Result::Ok(::autumn_web::reexports::http::StatusCode::NO_CONTENT),
                ::std::vec![(
                    "repository.delete.record".to_owned(),
                    __autumn_deleted_record_metadata,
                )],
            )
        }
    } else {
        quote! {
            #policy_check_delete_pre
            repo.delete_by_id(id).await?;
            Ok(::autumn_web::reexports::http::StatusCode::NO_CONTENT)
        }
    };
    let create_handler_expr = if has_policy {
        quote! { ::autumn_web::reexports::axum::routing::post(#create_fn) }
    } else {
        quote! {
            ::autumn_web::reexports::axum::routing::MethodRouter::<
                ::autumn_web::AppState, ::core::convert::Infallible
            >::layer(
                ::autumn_web::reexports::axum::routing::post(#create_fn),
                ::autumn_web::idempotency::IdempotencyReplayLayer,
            )
        }
    };
    let update_handler_expr = if has_policy {
        quote! { ::autumn_web::reexports::axum::routing::put(#update_fn) }
    } else {
        quote! {
            ::autumn_web::reexports::axum::routing::MethodRouter::<
                ::autumn_web::AppState, ::core::convert::Infallible
            >::layer(
                ::autumn_web::reexports::axum::routing::put(#update_fn),
                ::autumn_web::idempotency::IdempotencyReplayLayer,
            )
        }
    };
    let delete_handler_expr = if has_policy {
        quote! { ::autumn_web::reexports::axum::routing::delete(#delete_fn) }
    } else {
        quote! {
            ::autumn_web::reexports::axum::routing::MethodRouter::<
                ::autumn_web::AppState, ::core::convert::Infallible
            >::layer(
                ::autumn_web::reexports::axum::routing::delete(#delete_fn),
                ::autumn_web::idempotency::IdempotencyReplayLayer,
            )
        }
    };

    quote! {
        // ── Auto-generated REST API handlers ─────────────────

        #api_sink_assertion
        #policy_type_assertion
        #scope_type_assertion

        #vis async fn #list_fn(
            #list_session_state_args
            #list_pager_arg
            repo: #pg_name,
        ) -> ::autumn_web::AutumnResult<#list_return_type> {
            #scope_list_body
        }

        #list_schema_registration

        #[doc(hidden)]
        #vis fn #list_info() -> ::autumn_web::Route {
            #route_hook_registration
            ::autumn_web::Route {
                method: ::autumn_web::reexports::http::Method::GET,
                path: #api_path,
                handler: ::autumn_web::reexports::axum::routing::MethodRouter::<
                    ::autumn_web::AppState, ::core::convert::Infallible
                >::layer(
                    ::autumn_web::reexports::axum::routing::get(#list_fn),
                    ::autumn_web::idempotency::IdempotencyReplayLayer,
                ),
                name: ::core::stringify!(#list_fn),
                api_doc: ::autumn_web::openapi::ApiDoc {
                    method: "GET",
                    path: #api_path,
                    operation_id: ::core::stringify!(#list_fn),
                    success_status: 200,
                    // The pagination query/response envelopes are synthetic,
                    // runtime-inserted component schemas (`PageRequest` /
                    // `CursorRequest` / `<Model>Page` / `<Model>CursorPage`)
                    // with no addressable Rust type, so they carry no
                    // `type_name` identity and key off their short name.
                    query_schema: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: #list_query_schema_name,
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::None,
                        }
                    ),
                    response: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: #list_response_schema_name,
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::None,
                        }
                    ),
                    register_schemas: ::core::option::Option::Some(#list_schema_fn),
                    mcp_tool: #mcp_list_op,
                    ..::core::default::Default::default()
                },
                repository: ::core::option::Option::Some(::autumn_web::RepositoryApiMeta {
                    resource_type_name: #resource_type_name_lit,
                    api_path: #api_path_lit,
                    has_policy: #has_policy,
                    policy_check: #policy_check_fn,
                    scope_check: #list_scope_check_fn,
                }),
                idempotency: ::autumn_web::RouteIdempotency::ReplayThroughInner,
                timeout: ::autumn_web::RouteTimeout::Inherit,
                seo: ::autumn_web::seo::SeoRouteDefaults::EMPTY,
                api_version: ::core::option::Option::None,
                sunset_opt_out: false,
            }
        }

        #vis async fn #get_fn(
            #session_state_args
            ::autumn_web::extract::Path(id): ::autumn_web::extract::Path<i64>,
            repo: #pg_name,
        ) -> ::autumn_web::AutumnResult<::autumn_web::prelude::Json<#model_name>> {
            let record = repo.find_by_id(id).await?
                .ok_or_else(|| ::autumn_web::AutumnError::not_found_msg("not found"))?;
            #policy_check_show
            Ok(::autumn_web::prelude::Json(record))
        }

        #[doc(hidden)]
        #vis fn #get_info() -> ::autumn_web::Route {
            #route_hook_registration
            ::autumn_web::Route {
                method: ::autumn_web::reexports::http::Method::GET,
                path: #id_path,
                handler: ::autumn_web::reexports::axum::routing::MethodRouter::<
                    ::autumn_web::AppState, ::core::convert::Infallible
                >::layer(
                    ::autumn_web::reexports::axum::routing::get(#get_fn),
                    ::autumn_web::idempotency::IdempotencyReplayLayer,
                ),
                name: ::core::stringify!(#get_fn),
                api_doc: ::autumn_web::openapi::ApiDoc {
                    method: "GET",
                    path: #id_path,
                    operation_id: ::core::stringify!(#get_fn),
                    path_params: &["id"],
                    success_status: 200,
                    response: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: ::core::stringify!(#model_name),
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::Some(
                                ::autumn_web::openapi::type_name_of::<#model_name>
                            ),
                        }
                    ),
                    mcp_tool: #mcp_get_op,
                    ..::core::default::Default::default()
                },
                repository: ::core::option::Option::Some(::autumn_web::RepositoryApiMeta {
                    resource_type_name: #resource_type_name_lit,
                    api_path: #api_path_lit,
                    has_policy: #has_policy,
                    policy_check: #policy_check_fn,
                    scope_check: #non_list_scope_check_fn,
                }),
                idempotency: ::autumn_web::RouteIdempotency::ReplayThroughInner,
                timeout: ::autumn_web::RouteTimeout::Inherit,
                seo: ::autumn_web::seo::SeoRouteDefaults::EMPTY,
                api_version: ::core::option::Option::None,
                sunset_opt_out: false,
            }
        }

        #vis async fn #create_fn(
            #session_state_args
            repo: #pg_name,
            #create_payload_arg,
        ) -> #create_return_type {
            #create_body
        }

        #[doc(hidden)]
        #vis fn #create_info() -> ::autumn_web::Route {
            #route_hook_registration
            ::autumn_web::Route {
                method: ::autumn_web::reexports::http::Method::POST,
                path: #api_path,
                handler: #create_handler_expr,
                name: ::core::stringify!(#create_fn),
                api_doc: ::autumn_web::openapi::ApiDoc {
                    method: "POST",
                    path: #api_path,
                    operation_id: ::core::stringify!(#create_fn),
                    success_status: 201,
                    request_body: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: ::core::stringify!(#new_name),
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::Some(
                                ::autumn_web::openapi::type_name_of::<#new_name>
                            ),
                        }
                    ),
                    response: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: ::core::stringify!(#model_name),
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::Some(
                                ::autumn_web::openapi::type_name_of::<#model_name>
                            ),
                        }
                    ),
                    mcp_tool: #mcp_create_op,
                    ..::core::default::Default::default()
                },
                repository: ::core::option::Option::Some(::autumn_web::RepositoryApiMeta {
                    resource_type_name: #resource_type_name_lit,
                    api_path: #api_path_lit,
                    has_policy: #has_policy,
                    policy_check: #policy_check_fn,
                    scope_check: #non_list_scope_check_fn,
                }),
                idempotency: ::autumn_web::RouteIdempotency::ReplayThroughInner,
                timeout: ::autumn_web::RouteTimeout::Inherit,
                seo: ::autumn_web::seo::SeoRouteDefaults::EMPTY,
                api_version: ::core::option::Option::None,
                sunset_opt_out: false,
            }
        }

        #vis async fn #update_fn(
            #session_state_args
            ::autumn_web::extract::Path(id): ::autumn_web::extract::Path<i64>,
            repo: #pg_name,
            ::autumn_web::prelude::Json(patch): ::autumn_web::prelude::Json<#update_name>,
        ) -> #update_return_type {
            #update_body
        }

        #[doc(hidden)]
        #vis fn #update_info() -> ::autumn_web::Route {
            #route_hook_registration
            ::autumn_web::Route {
                method: ::autumn_web::reexports::http::Method::PUT,
                path: #id_path,
                handler: #update_handler_expr,
                name: ::core::stringify!(#update_fn),
                api_doc: ::autumn_web::openapi::ApiDoc {
                    method: "PUT",
                    path: #id_path,
                    operation_id: ::core::stringify!(#update_fn),
                    path_params: &["id"],
                    success_status: 200,
                    request_body: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: ::core::stringify!(#update_name),
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::Some(
                                ::autumn_web::openapi::type_name_of::<#update_name>
                            ),
                        }
                    ),
                    response: ::core::option::Option::Some(
                        ::autumn_web::openapi::SchemaEntry {
                            name: ::core::stringify!(#model_name),
                            kind: ::autumn_web::openapi::SchemaKind::Ref,
                            identity: ::core::option::Option::Some(
                                ::autumn_web::openapi::type_name_of::<#model_name>
                            ),
                        }
                    ),
                    mcp_tool: #mcp_update_op,
                    ..::core::default::Default::default()
                },
                repository: ::core::option::Option::Some(::autumn_web::RepositoryApiMeta {
                    resource_type_name: #resource_type_name_lit,
                    api_path: #api_path_lit,
                    has_policy: #has_policy,
                    policy_check: #policy_check_fn,
                    scope_check: #non_list_scope_check_fn,
                }),
                idempotency: ::autumn_web::RouteIdempotency::ReplayThroughInner,
                timeout: ::autumn_web::RouteTimeout::Inherit,
                seo: ::autumn_web::seo::SeoRouteDefaults::EMPTY,
                api_version: ::core::option::Option::None,
                sunset_opt_out: false,
            }
        }

        #vis async fn #delete_fn(
            #session_state_args
            ::autumn_web::extract::Path(id): ::autumn_web::extract::Path<i64>,
            repo: #pg_name,
        ) -> #delete_return_type {
            #delete_body
        }

        #[doc(hidden)]
        #vis fn #delete_info() -> ::autumn_web::Route {
            #route_hook_registration
            ::autumn_web::Route {
                method: ::autumn_web::reexports::http::Method::DELETE,
                path: #id_path,
                handler: #delete_handler_expr,
                name: ::core::stringify!(#delete_fn),
                api_doc: ::autumn_web::openapi::ApiDoc {
                    method: "DELETE",
                    path: #id_path,
                    operation_id: ::core::stringify!(#delete_fn),
                    path_params: &["id"],
                    success_status: 204,
                    mcp_tool: #mcp_delete_op,
                    ..::core::default::Default::default()
                },
                repository: ::core::option::Option::Some(::autumn_web::RepositoryApiMeta {
                    resource_type_name: #resource_type_name_lit,
                    api_path: #api_path_lit,
                    has_policy: #has_policy,
                    policy_check: #policy_check_fn,
                    scope_check: #non_list_scope_check_fn,
                }),
                idempotency: ::autumn_web::RouteIdempotency::ReplayThroughInner,
                timeout: ::autumn_web::RouteTimeout::Inherit,
                seo: ::autumn_web::seo::SeoRouteDefaults::EMPTY,
                api_version: ::core::option::Option::None,
                sunset_opt_out: false,
            }
        }

        // ── Path helpers for API routes ───────────────────────

        #[doc(hidden)]
        #vis fn #list_path_fn() -> ::std::string::String {
            #api_path.to_owned()
        }

        #[doc(hidden)]
        #vis fn #get_path_fn(id: impl ::std::fmt::Display) -> ::std::string::String {
            format!("{}/{}", #api_path, ::autumn_web::paths::encode_path_segment(id))
        }

        #[doc(hidden)]
        #vis fn #create_path_fn() -> ::std::string::String {
            #api_path.to_owned()
        }

        #[doc(hidden)]
        #vis fn #update_path_fn(id: impl ::std::fmt::Display) -> ::std::string::String {
            format!("{}/{}", #api_path, ::autumn_web::paths::encode_path_segment(id))
        }

        #[doc(hidden)]
        #vis fn #delete_path_fn(id: impl ::std::fmt::Display) -> ::std::string::String {
            format!("{}/{}", #api_path, ::autumn_web::paths::encode_path_segment(id))
        }
    }
}
