//! The retention sweep generated by `#[repository(..., retention(...))]`.
//!
//! This is not data access either. A retention policy compiles to a batched
//! background sweep and a companion task descriptor that the scheduler
//! collects — a background job that happens to delete rows, not part of the
//! repository's read/write surface.
//!
//! Kept beside [`crate::api`] for the same reason: `repository_macro` should
//! read as the database surface, and each of these is a separate concern
//! with its own gate.

// Every item here is crate-internal by design: this crate exports nothing but
// its proc-macro entry points, so `pub(crate)` can never widen to anything
// callers see. It is kept over `pub` to say so (clippy::redundant_pub_crate).
#![allow(clippy::redundant_pub_crate)]

use proc_macro2::TokenStream;
use quote::quote;
use syn::Ident;

use crate::repository::{
    DEFAULT_RETENTION_BATCH_SIZE, DEFAULT_RETENTION_SWEEP_INTERVAL, MAX_RETENTION_BATCHES_PER_RUN,
    RepoConfig,
};

/// What `repository_macro` must hand to the retention emitter.
pub(crate) struct RetentionInputs<'a> {
    /// The model the sweep deletes rows of.
    pub model_name: &'a Ident,
    /// The generated `Pg{Trait}` repository the sweep runs against.
    pub pg_name: &'a Ident,
    /// The diesel `table!` module the sweep queries.
    pub table_ident: &'a Ident,
    /// The table name, used verbatim for the scheduler task name.
    pub table_name: &'a str,
    /// Counter-cache specs, spliced so a swept row still decrements its parent.
    pub cc_specs: &'a TokenStream,
    /// Counter-cache presence flag.
    pub cc_has: &'a TokenStream,
    /// Counter-cache row serialization.
    pub cc_serialize: &'a TokenStream,
}

/// Emit the sweep method and its task registration, or nothing when the
/// repository declares no `retention(...)`.
// The same grandfathered allows `repository_macro` carries: this body was
// lifted out of it verbatim, so the lint surface moved with the code.
#[allow(clippy::too_many_lines, clippy::cognitive_complexity)]
pub(crate) fn emit_retention(
    config: &RepoConfig,
    inputs: &RetentionInputs<'_>,
) -> (TokenStream, TokenStream) {
    let RetentionInputs {
        model_name,
        pg_name,
        table_ident,
        table_name,
        cc_specs,
        cc_has,
        cc_serialize,
    } = inputs;

    let Some(spec) = &config.retention else {
        return (quote! {}, quote! {});
    };

    let batch_size = spec.batch_size.unwrap_or(DEFAULT_RETENTION_BATCH_SIZE);
    #[allow(clippy::cast_possible_wrap)]
    let batch_size_i64 = batch_size as i64;
    let every_str = spec
        .every
        .clone()
        .unwrap_or_else(|| DEFAULT_RETENTION_SWEEP_INTERVAL.to_string());
    let max_batches = MAX_RETENTION_BATCHES_PER_RUN;
    let model_name_str = model_name.to_string();
    // Table-qualified, not model-qualified: two modules can declare same-named
    // model types (`auth::Session`, `admin::Session`), which would collide on a
    // model-derived task name. The scheduler coordinates by name, so a collision
    // merges two policies' actuator state and can drop one under the Postgres
    // advisory-lock backend. Table names are already uniquely enforced by the
    // schema — but only as exact strings: Postgres allows distinct quoted tables
    // "Events" and "events", so `to_lowercase()` here would reintroduce the very
    // collision this prevents (#1342). Use `table_name` verbatim.
    let task_name_str = format!("retention-sweep-{table_name}");
    // When both `after` and `purge_deleted_after` are declared, split
    // the per-run batch budget between them instead of sharing one
    // counter: a shared counter starves whichever branch runs second
    // (the purge phase) whenever the first branch's backlog alone fills
    // the whole budget. Each branch still gets the full budget when
    // it's the only one declared.
    let both_branches = spec.after.is_some() && spec.purge_deleted_after.is_some();
    // `age_max_batches` is still a fixed per-run reservation for the
    // age phase's *primary* pass (never more than half the budget when
    // both branches are declared) so a huge age backlog can't starve
    // the purge phase entirely — the round-9 P1 fix.
    let age_max_batches = if both_branches {
        max_batches / 2
    } else {
        max_batches
    };

    // Age-based branch: soft-deletes on a soft_delete repository, never
    // re-touching an already soft-deleted row, and hard-deletes otherwise.
    // Absent unless `after` was declared.
    //
    // The query and mutation fragments are hoisted into `age_fragments` rather
    // than built inline, because the loop body is needed twice: once for the
    // capped primary pass below, and again — after `purge_block` runs and its
    // actual usage is known — as a reclaim pass letting age consume whatever
    // budget purge left unused (#1342), symmetric with the
    // purge-borrows-from-age fix. `build_age_loop` below builds each pass's
    // token stream from these shared fragments.
    let age_fragments = spec.after.as_ref().map(|_after| {
            let basis_ident = spec
                .basis
                .as_ref()
                .expect("validated by parse_repo_args: after requires basis")
                .clone();
            // Yields the number of rows the statement actually touched, not the
            // SELECT's candidate count, so a row that changed state between the
            // SELECT and this statement — a concurrent `restore()`, or, when `basis`
            // is a mutable column like `last_seen_at`, a concurrent update that
            // un-stales the row — is counted correctly in `rows_swept` rather than
            // over-reported. Re-checking `basis < __age_cutoff` here, not just `id`,
            // is what makes the second case safe.
            //
            // A counter-cached model swept by `retention(...)` must move its parent's
            // counter exactly as every other delete path does, or each swept live
            // child leaves its parent's stored count permanently inflated (#1342).
            // `counter_cache_before_delete_many` has to run on still-present,
            // still-live rows before the mutation, so the `#cc_has` arm first locks
            // (`FOR UPDATE`) the subset of `ids` still eligible under the recheck
            // filter — a candidate can have dropped out since the batch SELECT — then
            // decrements against exactly that locked set before mutating it. A model
            // with no counter cache keeps the original single-statement path.
            //
            // `scoped_immediate_transaction`, not `scoped_transaction`: on SQLite,
            // `maybe_for_update!` degrades to a plain read, so a deferred transaction
            // would not take a write lock until the first write below, leaving a
            // window for a concurrent writer to commit between the locked-ids SELECT
            // and that write — which SQLite reports as `SQLITE_BUSY_SNAPSHOT` rather
            // than waiting on the busy timeout. Every other generated read-then-write
            // path uses the immediate form for this reason.
            let apply_stmt = if config.soft_delete {
                quote! {
                    let __applied: u64 = if dry_run {
                        __n
                    } else if #cc_has {
                        #[allow(unused_imports)]
                        use ::autumn_web::reexports::diesel_async::AsyncConnection as _;
                        #[allow(unused_imports)]
                        use ::autumn_web::reexports::scoped_futures::ScopedFutureExt as _;
                        let __now = ::autumn_web::time::ClockSource::now(state.clock()).naive_utc();
                        ::autumn_web::__private::scoped_immediate_transaction::<u64, ::autumn_web::AutumnError, _>(
                            &mut *conn,
                            |conn| async move {
                                // `order(id.asc())` before the `FOR UPDATE`
                                // lock (#1342): on Postgres a sweep here can
                                // race a normal `delete_many` locking an
                                // overlapping batch of the same counter-cached
                                // children. `delete_many`'s own
                                // `counter_cache_before_delete_many` locks
                                // ascending by id to avoid a deadlock, but that
                                // only helps if every locker does the same.
                                // Without it here, the two transactions could
                                // take the same rows in opposite orders and one
                                // would be aborted.
                                #cc_serialize
                                let __locked_ids: ::std::vec::Vec<i64> = ::autumn_web::maybe_for_update!(
                                    #table_ident::table
                                        .filter(#table_ident::id.eq_any(ids))
                                        .filter(#table_ident::#basis_ident.lt(__age_cutoff))
                                        .filter(#table_ident::deleted_at.is_null())
                                        .order(#table_ident::id.asc())
                                        .select(#table_ident::id)
                                )
                                .load::<i64>(conn)
                                .await
                                .map_err(::autumn_web::AutumnError::from)?;
                                ::autumn_web::repository::counter_cache_before_delete_many(
                                    conn, #cc_specs, &__locked_ids,
                                ).await?;
                                let __n2 = ::autumn_web::reexports::diesel::update(
                                    #table_ident::table.filter(#table_ident::id.eq_any(&__locked_ids))
                                )
                                .set(#table_ident::deleted_at.eq(::core::option::Option::Some(__now)))
                                .execute(conn)
                                .await
                                .map_err(::autumn_web::AutumnError::from)?;
                                ::core::result::Result::Ok(__n2 as u64)
                            }
                            .scope_boxed(),
                        )
                        .await?
                    } else {
                        let __now = ::autumn_web::time::ClockSource::now(state.clock()).naive_utc();
                        ::autumn_web::reexports::diesel::update(
                            #table_ident::table
                                .filter(#table_ident::id.eq_any(ids))
                                .filter(#table_ident::#basis_ident.lt(__age_cutoff))
                                .filter(#table_ident::deleted_at.is_null())
                        )
                        .set(#table_ident::deleted_at.eq(::core::option::Option::Some(__now)))
                        .execute(&mut conn)
                        .await
                        .map_err(::autumn_web::AutumnError::from)? as u64
                    };
                }
            } else {
                quote! {
                    let __applied: u64 = if dry_run {
                        __n
                    } else if #cc_has {
                        #[allow(unused_imports)]
                        use ::autumn_web::reexports::diesel_async::AsyncConnection as _;
                        #[allow(unused_imports)]
                        use ::autumn_web::reexports::scoped_futures::ScopedFutureExt as _;
                        ::autumn_web::__private::scoped_immediate_transaction::<u64, ::autumn_web::AutumnError, _>(
                            &mut *conn,
                            |conn| async move {
                                // Locked ascending by id, matching the
                                // soft-delete branch's identical fix above
                                // (#1342 review round 22).
                                #cc_serialize
                                let __locked_ids: ::std::vec::Vec<i64> = ::autumn_web::maybe_for_update!(
                                    #table_ident::table
                                        .filter(#table_ident::id.eq_any(ids))
                                        .filter(#table_ident::#basis_ident.lt(__age_cutoff))
                                        .order(#table_ident::id.asc())
                                        .select(#table_ident::id)
                                )
                                .load::<i64>(conn)
                                .await
                                .map_err(::autumn_web::AutumnError::from)?;
                                ::autumn_web::repository::counter_cache_before_delete_many(
                                    conn, #cc_specs, &__locked_ids,
                                ).await?;
                                let __n2 = ::autumn_web::reexports::diesel::delete(
                                    #table_ident::table.filter(#table_ident::id.eq_any(&__locked_ids))
                                )
                                .execute(conn)
                                .await
                                .map_err(::autumn_web::AutumnError::from)?;
                                ::core::result::Result::Ok(__n2 as u64)
                            }
                            .scope_boxed(),
                        )
                        .await?
                    } else {
                        ::autumn_web::reexports::diesel::delete(
                            #table_ident::table
                                .filter(#table_ident::id.eq_any(ids))
                                .filter(#table_ident::#basis_ident.lt(__age_cutoff))
                        )
                        .execute(&mut conn)
                        .await
                        .map_err(::autumn_web::AutumnError::from)? as u64
                    };
                }
            };
            let not_already_deleted_filter = if config.soft_delete {
                quote! { .filter(#table_ident::deleted_at.is_null()) }
            } else {
                quote! {}
            };
            (basis_ident, apply_stmt, not_already_deleted_filter)
        });

    // Cutoff plus cursor/counter state shared by both the primary age
    // pass below and the round-13 reclaim pass spliced in after
    // `purge_block` — hoisted out of either loop so the reclaim pass
    // resumes from the primary pass's cursor instead of rescanning.
    // `__age_capped` is only meaningful (and only declared) when a
    // reclaim pass could actually run.
    let age_cutoff_and_state_decl = spec.after.as_ref().map_or_else(
        || quote! {},
        |after| {
            let capped_decl = if both_branches {
                quote! { let mut __age_capped: bool = false; }
            } else {
                quote! {}
            };
            quote! {
                let __age_duration = ::autumn_web::task::parse_duration(#after)
                    .expect(concat!(
                        "invalid duration in #[repository(..., retention(after = \"",
                        #after,
                        "\"))]"
                    ));
                let __age_chrono =
                    ::autumn_web::reexports::chrono::Duration::from_std(__age_duration)
                        .expect("retention `after` duration out of range");
                // Checked, not `-` (#1342): `after` fitting in
                // `chrono::Duration`'s range does not mean subtracting it
                // from this clock reading stays inside `NaiveDateTime`'s
                // range. A custom clock near `NaiveDateTime::MIN` — a test
                // clock, or a misconfigured system clock — can underflow
                // even for a boot-validated `after`. `-` panics on overflow;
                // this fails with the same actionable message boot validation
                // uses for the config-level check.
                let __age_cutoff = ::autumn_web::time::ClockSource::now(state.clock())
                    .naive_utc()
                    .checked_sub_signed(__age_chrono)
                    .expect(concat!(
                        "retention `after` duration is too large to compute a valid cutoff \
                         from the current time in #[repository(..., retention(after = \"",
                        #after,
                        "\"))]"
                    ));
                // `Option<i64>`, not a sentinel `i64` floor: no `i64` is
                // guaranteed below every possible id — `i64::MIN` is itself a
                // legal id, and `id.gt(i64::MIN)` would exclude exactly that
                // row — and this repository's PK convention does not forbid
                // ids at or below zero, as a manual import can produce. `None`
                // means "first page, no lower bound"; every later page,
                // including the reclaim pass's first, carries a real cursor.
                let mut __age_last_id: ::core::option::Option<i64> = ::core::option::Option::None;
                let mut __age_batches: u32 = 0;
                #capped_decl
            }
        },
    );

    let mark_capped_true = if both_branches {
        quote! { __age_capped = true; }
    } else {
        quote! {}
    };
    let mark_capped_false = if both_branches {
        quote! { __age_capped = false; }
    } else {
        quote! {}
    };

    // One bounded pass over the age loop, capped at `cap_expr` (a
    // runtime `u32` expression). Reads/writes the outer
    // `__age_last_id`/`__age_batches` declared above rather than
    // re-declaring locals, so calling this twice — the primary pass
    // below, then the round-13 reclaim pass after `purge_block` —
    // resumes the second call from the first's cursor instead of
    // rescanning.
    let build_age_loop = |cap_expr: TokenStream| -> TokenStream {
        let Some((basis_ident, apply_stmt, not_already_deleted_filter)) = age_fragments.as_ref()
        else {
            return quote! {};
        };
        quote! {
            {
                let __age_cap_this_pass: u32 = #cap_expr;
                loop {
                    if __age_batches >= __age_cap_this_pass {
                        #mark_capped_true
                        break;
                    }
                    let mut __query = #table_ident::table
                        .into_boxed()
                        .filter(#table_ident::#basis_ident.lt(__age_cutoff))
                        #not_already_deleted_filter;
                    if let ::core::option::Option::Some(__last) = __age_last_id {
                        __query = __query.filter(#table_ident::id.gt(__last));
                    }
                    let ids: ::std::vec::Vec<i64> = __query
                        .order(#table_ident::id.asc())
                        .select(#table_ident::id)
                        .limit(#batch_size_i64)
                        .load::<i64>(&mut conn)
                        .await
                        .map_err(::autumn_web::AutumnError::from)?;
                    if ids.is_empty() {
                        #mark_capped_false
                        break;
                    }
                    let __n = ids.len() as u64;
                    __age_last_id = ::core::option::Option::Some(
                        *ids.last().expect("ids non-empty"),
                    );
                    #apply_stmt
                    rows_swept += __applied;
                    __age_batches += 1;
                    if __n < #batch_size_i64 as u64 {
                        #mark_capped_false
                        break;
                    }
                    if __age_batches >= __age_cap_this_pass {
                        #mark_capped_true
                        break;
                    }
                }
            }
        }
    };

    let age_block = build_age_loop(quote! { #age_max_batches });

    // Purge's cap is computed at *runtime*, after the age phase's
    // primary pass finishes, as the total budget minus whatever that
    // pass actually used — never less than its guaranteed floor (age's
    // primary pass can never use more than its own fixed
    // `age_max_batches` cap), but free to claim everything age's
    // primary pass left unused (#1342 review round 11).
    let purge_max_batches_expr = if both_branches {
        quote! { (#max_batches).saturating_sub(__age_batches) }
    } else {
        quote! { #max_batches }
    };
    // Read by the round-13 age reclaim pass below, to compute how much
    // of the shared budget purge left unused after age's primary pass
    // ceded it some (or all) of the floor purge didn't need.
    let purge_batches_used_decl = if both_branches {
        quote! { let mut __purge_batches_used: u32 = 0; }
    } else {
        quote! {}
    };
    let purge_batches_used_write = if both_branches {
        quote! { __purge_batches_used = __batches; }
    } else {
        quote! {}
    };

    // Purge branch: always a hard DELETE of rows soft-deleted longer
    // than `purge_deleted_after`. Absent unless declared (and only
    // ever declared alongside `soft_delete` — enforced above).
    let purge_block = spec.purge_deleted_after.as_ref().map_or_else(
                || quote! {},
                |purge_after| {
                    quote! {
                        {
                            let __purge_duration = ::autumn_web::task::parse_duration(#purge_after)
                                .expect(concat!(
                                    "invalid duration in #[repository(..., retention(purge_deleted_after = \"",
                                    #purge_after,
                                    "\"))]"
                                ));
                            let __purge_chrono =
                                ::autumn_web::reexports::chrono::Duration::from_std(__purge_duration)
                                    .expect("retention `purge_deleted_after` duration out of range");
                            // Checked, not `-` (#1342 review round 16): see
                            // the age branch's identical cutoff computation
                            // for why a boot-validated duration can still
                            // underflow against a particular clock reading.
                            let __cutoff = ::autumn_web::time::ClockSource::now(state.clock())
                                .naive_utc()
                                .checked_sub_signed(__purge_chrono)
                                .expect(concat!(
                                    "retention `purge_deleted_after` duration is too large to \
                                     compute a valid cutoff from the current time in \
                                     #[repository(..., retention(purge_deleted_after = \"",
                                    #purge_after,
                                    "\"))]"
                                ));
                            // Computed at runtime, not a fixed macro-time
                            // half-share (#1342 review round 11): lets the
                            // purge phase claim whatever budget the age
                            // phase didn't use, while never exceeding the
                            // total per-run cap.
                            let __purge_max_batches: u32 = #purge_max_batches_expr;
                            let mut __last_id: ::core::option::Option<i64> = ::core::option::Option::None;
                            let mut __batches: u32 = 0;
                            loop {
                                if __batches >= __purge_max_batches {
                                    break;
                                }
                                let mut __query = #table_ident::table
                                    .into_boxed()
                                    .filter(#table_ident::deleted_at.lt(__cutoff));
                                if let ::core::option::Option::Some(__last) = __last_id {
                                    __query = __query.filter(#table_ident::id.gt(__last));
                                }
                                let ids: ::std::vec::Vec<i64> = __query
                                    .order(#table_ident::id.asc())
                                    .select(#table_ident::id)
                                    .limit(#batch_size_i64)
                                    .load::<i64>(&mut conn)
                                    .await
                                    .map_err(::autumn_web::AutumnError::from)?;
                                if ids.is_empty() {
                                    break;
                                }
                                let __n = ids.len() as u64;
                                __last_id = ::core::option::Option::Some(
                                    *ids.last().expect("ids non-empty"),
                                );
                                // Re-check `deleted_at < __cutoff` at delete
                                // time, not just `id`: a row concurrently
                                // `restore()`d between the SELECT above and this
                                // DELETE must survive rather than be purged out
                                // from under the restore. The `#cc_has` arm also
                                // locks the still-eligible subset and runs
                                // `counter_cache_before_delete_many` on it before
                                // purging. That is normally a no-op — the row's
                                // counter moved when it was soft-deleted — but it
                                // keeps the purge path symmetric with the age
                                // branch, and correct if that invariant changes.
                                let __applied: u64 = if dry_run {
                                    __n
                                } else if #cc_has {
                                    #[allow(unused_imports)]
                                    use ::autumn_web::reexports::diesel_async::AsyncConnection as _;
                                    #[allow(unused_imports)]
                                    use ::autumn_web::reexports::scoped_futures::ScopedFutureExt as _;
                                    ::autumn_web::__private::scoped_immediate_transaction::<u64, ::autumn_web::AutumnError, _>(
                                        &mut *conn,
                                        |conn| async move {
                                            // Locked ascending by id, matching
                                            // the age branches' identical fix
                                            // above (#1342 review round 22).
                                            #cc_serialize
                                            let __locked_ids: ::std::vec::Vec<i64> = ::autumn_web::maybe_for_update!(
                                                #table_ident::table
                                                    .filter(#table_ident::id.eq_any(ids))
                                                    .filter(#table_ident::deleted_at.lt(__cutoff))
                                                    .order(#table_ident::id.asc())
                                                    .select(#table_ident::id)
                                            )
                                            .load::<i64>(conn)
                                            .await
                                            .map_err(::autumn_web::AutumnError::from)?;
                                            ::autumn_web::repository::counter_cache_before_delete_many(
                                                conn, #cc_specs, &__locked_ids,
                                            ).await?;
                                            let __n2 = ::autumn_web::reexports::diesel::delete(
                                                #table_ident::table.filter(#table_ident::id.eq_any(&__locked_ids))
                                            )
                                            .execute(conn)
                                            .await
                                            .map_err(::autumn_web::AutumnError::from)?;
                                            ::core::result::Result::Ok(__n2 as u64)
                                        }
                                        .scope_boxed(),
                                    )
                                    .await?
                                } else {
                                    ::autumn_web::reexports::diesel::delete(
                                        #table_ident::table
                                            .filter(#table_ident::id.eq_any(ids))
                                            .filter(#table_ident::deleted_at.lt(__cutoff))
                                    )
                                    .execute(&mut conn)
                                    .await
                                    .map_err(::autumn_web::AutumnError::from)? as u64
                                };
                                rows_swept += __applied;
                                __batches += 1;
                                if __n < #batch_size_i64 as u64 || __batches >= __purge_max_batches {
                                    break;
                                }
                            }
                            #purge_batches_used_write
                        }
                    }
                },
            );

    // Symmetric with round 11's purge-borrows-from-age fix (#1342
    // review round 13): if age's primary pass hit its cap — there may
    // be more matching rows still waiting — and purge didn't use its
    // whole share, let age reclaim whatever purge left unused instead
    // of leaving it idle until the next scheduled tick. Resumes from
    // the primary pass's cursor via the shared `__age_last_id`/
    // `__age_batches` state rather than rescanning.
    let age_reclaim_block = if both_branches {
        let reclaim_loop =
            build_age_loop(quote! { (#max_batches).saturating_sub(__purge_batches_used) });
        quote! {
            if __age_capped {
                #reclaim_loop
            }
        }
    } else {
        quote! {}
    };

    // Validate `after`/`purge_deleted_after` at task-registration time (boot),
    // matching `every` below. Otherwise a typo'd unit such as "30dd" compiles
    // and boots cleanly and panics only on the sweep's first scheduled tick,
    // well after anyone was watching the deploy.
    //
    // This also validates the `chrono::Duration` conversion, not just
    // `parse_duration`'s `std::time::Duration` (#1342): a value that parses as
    // a `std::time::Duration` — a huge second count like
    // `"18446744073709551615s"` — can still overflow `chrono::Duration`, which
    // the sweep loop converts to when computing the cutoff.
    //
    // `chrono::Duration::from_std` checks that a duration fits chrono's range,
    // but a value that fits — `after = "100000000d"`, about 274,000 years — can
    // still place the cutoff outside `NaiveDateTime`'s range once subtracted
    // from a clock reading. That is checked against the ambient clock
    // (`time::ambient_now`, issue #2967), not the app's `ClockSource`, which
    // `task_info()` — a plain `fn() -> TaskInfo` with no `state` parameter —
    // cannot reach. It is a sanity bound: an `after` that large overflows
    // whatever "now" turns out to be.
    let after_boot_validation = spec.after.as_ref().map_or_else(
        || quote! {},
        |after| {
            quote! {
                {
                    let __duration = ::autumn_web::task::parse_duration(#after)
                        .expect(concat!(
                            "invalid duration in #[repository(..., retention(after = \"",
                            #after,
                            "\"))]"
                        ));
                    let __chrono_duration =
                        ::autumn_web::reexports::chrono::Duration::from_std(__duration)
                            .expect(concat!(
                                "retention `after` duration out of range in \
                                 #[repository(..., retention(after = \"",
                                #after,
                                "\"))]"
                            ));
                    ::autumn_web::time::ambient_now()
                        .naive_utc()
                        .checked_sub_signed(__chrono_duration)
                        .expect(concat!(
                            "retention `after` duration is too large to compute a valid \
                             cutoff (overflows the representable date range) in \
                             #[repository(..., retention(after = \"",
                            #after,
                            "\"))]"
                        ));
                }
            }
        },
    );
    let purge_boot_validation = spec.purge_deleted_after.as_ref().map_or_else(
            || quote! {},
            |purge_after| {
                quote! {
                    {
                        let __duration = ::autumn_web::task::parse_duration(#purge_after)
                            .expect(concat!(
                                "invalid duration in #[repository(..., retention(purge_deleted_after = \"",
                                #purge_after,
                                "\"))]"
                            ));
                        let __chrono_duration =
                            ::autumn_web::reexports::chrono::Duration::from_std(__duration)
                                .expect(concat!(
                                    "retention `purge_deleted_after` duration out of range in \
                                     #[repository(..., retention(purge_deleted_after = \"",
                                    #purge_after,
                                    "\"))]"
                                ));
                        ::autumn_web::time::ambient_now()
                            .naive_utc()
                            .checked_sub_signed(__chrono_duration)
                            .expect(concat!(
                                "retention `purge_deleted_after` duration is too large to \
                                 compute a valid cutoff (overflows the representable date \
                                 range) in #[repository(..., retention(purge_deleted_after = \"",
                                #purge_after,
                                "\"))]"
                            ));
                    }
                }
            },
        );
    // The `dependents.is_empty()` check in `parse_repo_args` sees only
    // repository-attribute `dependent(...)`. A model can also declare
    // `#[has_many(..., dependent = ...)]` or `#[has_one(...)]` directly, in a
    // separate `#[model]` invocation this macro cannot see at compile time,
    // resolved instead through the same runtime `Model::dependents()` the normal
    // cascade delete path drives. The sweep mutates rows directly and never
    // calls it, so the orphan and restrict-bypass risk the repository-attribute
    // rejection exists for applies here too. Check at boot, like the duration
    // validation above, rather than on the first scheduled tick (#1342).
    let model_dependents_boot_validation = quote! {
        {
            #[allow(unused_imports)]
            use ::autumn_web::repository::AutumnDependents as _;
            assert!(
                #model_name::dependents().is_empty(),
                "retention(...) on {} does not support a model-declared \
                 #[has_many(..., dependent = ...)] (or #[has_one(...)]) association yet: \
                 the sweep mutates rows directly and does not run the cascade-aware delete \
                 path Model::dependents() drives, so a hard-delete sweep could orphan \
                 children (or silently ignore an on_delete = restrict rule) and a \
                 soft-delete sweep would leave active children attached to a swept parent. \
                 Remove the model-side `dependent = ...`, or call \
                 delete_many(ids)/delete_by_id(id) yourself from a hand-written \
                 #[scheduled] sweep for now",
                ::core::stringify!(#model_name)
            );
        }
    };
    // `parse_repo_args` rejects only `batch_size` values that overflow `i64`,
    // the Postgres `LIMIT` bound. It cannot know the bind-parameter limit: that
    // is backend-specific (`MAX_BIND_PARAMS` is 32766 on SQLite, 65535 on
    // Postgres) and which backend is active is a Cargo feature of the consuming
    // crate, invisible to a proc macro that sees only its own crate's features.
    // Each swept batch binds one parameter per row id (`id.eq_any(ids)`) plus up
    // to two more — the age or purge cutoff, and for a soft-delete age sweep the
    // new `deleted_at` timestamp — so a `batch_size` within 2 of the backend's
    // limit would compile and boot cleanly, then fail every real sweep with "too
    // many SQL variables". `MAX_BIND_PARAMS` resolves per backend at the
    // boot-time assert below, because that is evaluated in the consuming crate
    // where the feature choice is visible (#1342).
    let batch_size_bind_boot_validation = quote! {
        assert!(
            (#batch_size_i64 as u64) + 2 <= ::autumn_web::repository::MAX_BIND_PARAMS as u64,
            "retention(batch_size = {}) leaves no headroom under this backend's \
             bind-parameter limit ({}): each swept batch binds one parameter per row id \
             plus the cutoff (and, for a soft-delete age sweep, the new deleted_at \
             timestamp), so a sweep this large would compile and boot cleanly but fail \
             every real run with \"too many SQL variables\". Lower `batch_size`, or remove \
             it for the default of {}",
            #batch_size_i64,
            ::autumn_web::repository::MAX_BIND_PARAMS,
            #DEFAULT_RETENTION_BATCH_SIZE
        );
    };
    let retention_duration_boot_validation = quote! {
        #after_boot_validation
        #purge_boot_validation
        #model_dependents_boot_validation
        #batch_size_bind_boot_validation
    };

    let methods = quote! {
        /// Run this model's declared `retention(...)` policy once,
        /// deleting (or soft-deleting) stale rows in bounded batches.
        /// Registered as a fleet-coordinated scheduled task
        /// automatically — apps never call this directly. See
        /// `docs/guide/retention-sweeps.md`.
        #[doc(hidden)]
        pub async fn __autumn_retention_sweep(
            state: &::autumn_web::AppState,
        ) -> ::autumn_web::AutumnResult<::autumn_web::retention::RetentionSweepReport> {
            Self::__autumn_retention_run(state, false).await
        }

        /// Count (never delete) the rows this policy would sweep
        /// right now. Powers `autumn retention --dry-run`.
        #[doc(hidden)]
        pub fn __autumn_retention_dry_run(
            state: ::autumn_web::AppState,
        ) -> ::std::pin::Pin<::std::boxed::Box<
            dyn ::std::future::Future<
                Output = ::autumn_web::AutumnResult<::autumn_web::retention::RetentionSweepReport>,
            > + Send,
        >> {
            ::std::boxed::Box::pin(async move {
                Self::__autumn_retention_run(&state, true).await
            })
        }

        #[doc(hidden)]
        async fn __autumn_retention_run(
            state: &::autumn_web::AppState,
            dry_run: bool,
        ) -> ::autumn_web::AutumnResult<::autumn_web::retention::RetentionSweepReport> {
            use ::autumn_web::db::DbState as _;
            use ::autumn_web::reexports::diesel::prelude::*;
            use ::autumn_web::reexports::diesel_async::RunQueryDsl;
            use ::autumn_web::time::ClockSource as _;

            let __started = state.monotonic();
            let pool = state
                .pool()
                .ok_or_else(|| {
                    ::autumn_web::AutumnError::service_unavailable_msg(
                        "retention sweep: no database pool configured",
                    )
                })?
                .clone();
            let repo = Self::with_pool_untracked(pool);
            let mut conn = repo.__autumn_acquire_conn().await?;
            let mut rows_swept: u64 = 0;
            #age_cutoff_and_state_decl
            #purge_batches_used_decl

            // Each batch commits independently — no transaction spans the run —
            // so a mid-run failure leaves earlier batches committed. Capturing
            // the sweep's `Result` here, rather than letting a bare `?` inside
            // these blocks return straight out of the function, lets the partial
            // `rows_swept` reach `log_retention_sweep` below before the error
            // propagates (#1342). Otherwise those committed rows would be missing
            // from `retention_sweep_rows_total` and no structured report would
            // record the partial work.
            let __sweep_result: ::autumn_web::AutumnResult<()> = async {
                #age_block
                #purge_block
                #age_reclaim_block
                ::core::result::Result::Ok(())
            }
            .await;

            #[allow(clippy::cast_possible_truncation)]
            let duration_ms =
                state.monotonic().saturating_duration_since(__started).as_millis() as u64;
            let report = ::autumn_web::retention::RetentionSweepReport {
                model: #model_name_str.to_string(),
                table: #table_name.to_string(),
                rows_swept,
                duration_ms,
                dry_run,
            };
            match __sweep_result {
                ::core::result::Result::Ok(()) => ::core::result::Result::Ok(report),
                ::core::result::Result::Err(error) => {
                    ::autumn_web::retention::log_retention_sweep(&report);
                    ::core::result::Result::Err(error)
                }
            }
        }

        /// Builds the recurring `TaskInfo` `autumn_web::retention`
        /// auto-registers with the scheduler.
        ///
        /// Validates every declared duration string up front — `after`,
        /// `purge_deleted_after`, and `every` all fail loudly here, at
        /// boot, rather than a `basis`/`purge_deleted_after` typo only
        /// surfacing on the sweep's first scheduled tick (up to `every`
        /// later).
        #[doc(hidden)]
        pub fn __autumn_retention_task_info() -> ::autumn_web::task::TaskInfo {
            #retention_duration_boot_validation
            ::autumn_web::task::TaskInfo {
                name: #task_name_str.to_string(),
                schedule: ::autumn_web::task::Schedule::FixedDelay(
                    ::autumn_web::task::parse_duration(#every_str)
                        .expect(concat!(
                            "invalid duration in #[repository(..., retention(every = \"",
                            #every_str,
                            "\"))]"
                        ))
                ),
                coordination: ::autumn_web::task::TaskCoordination::Fleet,
                handler: |state: ::autumn_web::AppState| {
                    ::std::boxed::Box::pin(async move {
                        let report = Self::__autumn_retention_sweep(&state).await?;
                        ::autumn_web::retention::log_retention_sweep(&report);
                        Ok(())
                    })
                },
            }
        }
    };

    let registration = quote! {
        ::autumn_web::reexports::inventory::submit! {
            ::autumn_web::retention::RetentionSweepDescriptor {
                model_name: stringify!(#model_name),
                table_name: #table_name,
                task_info: #pg_name::__autumn_retention_task_info,
                dry_run: #pg_name::__autumn_retention_dry_run,
            }
        }
    };

    (methods, registration)
}
