//! `routes![]` collection macro implementation.
//!
//! Expands `routes![handler_a, handler_b]` into a `Vec<Route>` by calling
//! the companion `__autumn_route_info_{name}()` functions generated by the
//! route attribute macros.

use proc_macro2::TokenStream;

/// Expand a comma-separated list of handler paths into a `Vec<Route>`.
///
/// Each path's last segment is transformed from `name` to
/// `__autumn_route_info_name`, so module-qualified paths like `users::list`
/// become `users::__autumn_route_info_list`.
pub fn routes_macro(input: TokenStream) -> TokenStream {
    crate::collect::collect_companions(input, "__autumn_route_info_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    #[test]
    fn test_routes_macro() {
        let input = quote! { handler_a, users::handler_b };
        let result = routes_macro(input);
        let result_str = result.to_string();

        assert!(result_str.contains("__autumn_route_info_handler_a"));
        assert!(result_str.contains("users :: __autumn_route_info_handler_b"));
    }
}
