use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::AutumnResult;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
/// Metadata for a single WASM island component.
///
/// Maps a component name (like `"Counter"`) to the DOM ID where it
/// should be mounted.
pub struct WasmIslandManifestEntry {
    pub mount_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
/// WASM asset manifest generated by `autumn build`.
///
/// Contains paths to the compiled JavaScript and WASM entrypoints,
/// as well as the mount points for each island component.
pub struct WasmManifest {
    pub entry_js: Option<String>,
    pub entry_wasm: Option<String>,
    #[serde(default)]
    pub islands: BTreeMap<String, WasmIslandManifestEntry>,
}

impl WasmManifest {
    /// Load a WASM manifest from disk.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be read or if the JSON payload
    /// cannot be deserialized into [`WasmManifest`].
    pub fn load(path: &Path) -> AutumnResult<Self> {
        let bytes = std::fs::read(path)?;
        Ok(serde_json::from_slice(&bytes)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_reads_manifest_from_disk() {
        let temp = tempfile::NamedTempFile::new().expect("temp file");
        std::fs::write(
            temp.path(),
            r#"{"entry_js":"/static/client.js","entry_wasm":"/static/client_bg.wasm","islands":{"counter":{"mount_id":"counter-root"}}}"#,
        )
        .expect("write manifest");

        let manifest = WasmManifest::load(temp.path()).expect("load manifest");

        assert_eq!(manifest.entry_js.as_deref(), Some("/static/client.js"));
        assert_eq!(
            manifest.entry_wasm.as_deref(),
            Some("/static/client_bg.wasm")
        );
        assert_eq!(manifest.islands["counter"].mount_id, "counter-root");
    }

    #[test]
    fn load_rejects_invalid_json() {
        let temp = tempfile::NamedTempFile::new().expect("temp file");
        std::fs::write(temp.path(), "{ not json").expect("write manifest");

        assert!(WasmManifest::load(temp.path()).is_err());
    }

    #[test]
    fn load_missing_manifest_returns_error() {
        let missing = std::path::Path::new("definitely-not-a-real-manifest.json");

        assert!(WasmManifest::load(missing).is_err());
    }
}
