-- `/author/{username}` (`content::published_posts_by_author` and the
-- `has_public_content` gate ahead of it, `content::published_post_count_by_author`
-- — both in `examples/cms/src/content.rs`) filter `posts` by
-- `(author_id, status, post_type)` and, for the row fetch, order by
-- `published_at DESC, id DESC` with a `LIMIT`/`OFFSET`.
--
-- Neither existing index serves that combination: `idx_posts_author` covers
-- only `author_id` (no status/order), and `idx_posts_status_published`
-- (`status`, `published_at DESC`) gives the sort order but not the author
-- filter, so the planner has to walk it in `published_at` order filtering out
-- every non-matching author's row until it collects enough for the page.
-- That is cheap for a prolific author (most rows already match) and
-- increasingly expensive the smaller an author's share of the site's
-- published content is — exactly the common case on a real multi-author
-- site, where a handful of staff writers account for most of the archive and
-- most bylines are occasional contributors. See
-- `docs/reports/2026-09-25-ledger-cms-author-archive-index/` for the
-- measured buffers/rows-read delta across three author-share tiers.
--
-- `INCLUDE (post_type)` carries the one remaining filter column that isn't
-- part of the key, so the *count* query
-- (`published_post_count_by_author`'s gate check, and
-- `published_posts_by_author`'s own internal count — identical SQL shape)
-- can be answered as an Index Only Scan once autovacuum has set the
-- visibility map: no heap fetch per matching row at all, versus one per row
-- today. That matters more than it looks: the count has no `LIMIT` to
-- exploit, so it is the *more* expensive of the two queries for a
-- high-share author (measured: 7,426 of a prolific author's 7,440 total
-- buffers were the count, not the row fetch) even though the row fetch is
-- the one whose plan visibly changes shape by author share. The row fetch
-- (`SELECT posts.*`) still needs a heap visit per row it returns, but
-- `LIMIT` already bounds that to the page size once the index gives it
-- correctly-ordered candidates. See
-- `docs/reports/2026-09-25-ledger-cms-author-archive-index/` for the
-- measured buffers/rows-read delta across three author-share tiers.
--
-- `CONCURRENTLY` (needs `run_in_transaction = false` in this migration's
-- `metadata.toml` — Postgres refuses `CREATE INDEX CONCURRENTLY` inside a
-- transaction block) so this never takes more than a `SHARE UPDATE
-- EXCLUSIVE` lock on `posts`, which does not block reads or writes.
--
-- Deliberately no `IF NOT EXISTS`: a cancelled or deadlocked concurrent build
-- can leave `idx_posts_author_status_published` present but INVALID. With
-- `IF NOT EXISTS`, a retried migration would see the name already taken,
-- skip creation, and diesel would record the migration as applied — leaving
-- the app permanently without a usable index and no signal that anything is
-- wrong. Without it, a retry hits "relation already exists" and fails loudly,
-- so an operator has to `DROP INDEX CONCURRENTLY idx_posts_author_status_published`
-- and rerun before this can silently succeed.
CREATE INDEX CONCURRENTLY idx_posts_author_status_published
    ON posts (author_id, status, published_at DESC) INCLUDE (post_type);
