// ── v0.2 Feature: #[repository] macro ───────────────────────────
//
// Generates PgSubredditRepository and PgPostRepository with:
//   - Auto-generated CRUD methods (find_by_id, find_all, save, etc.)
//   - Derived queries parsed from method signatures
//   - FromRequestParts extractor (use as handler parameter)
//   - Optional REST API handler generation with `api = "..."`
//   - Optional mutation hooks with `hooks = ...`
//   - `broadcasts = "posts"` on PostRepository publishes hx-swap-oob fragments
//     over the "posts" SSE topic when mutations go through PgPostRepository.
//     Note: the HTML form routes (submit/edit/delete) write directly with Diesel
//     and therefore do not trigger broadcasts.  Broadcasts fire for REST API
//     mutations at /api/posts.  To broadcast from HTML routes too, call
//     state.broadcast().publish_oob(...) after each Diesel mutation.

use crate::hooks::{PostHooks, SubredditHooks};
use crate::models::{
    NewPost, NewSubreddit, NewVote, Post, PostDraftExt, Subreddit, SubredditDraftExt, UpdatePost,
    UpdateSubreddit, UpdateVote, Vote,
};
use crate::schema::{posts, subreddits, votes};

#[autumn_web::repository(Subreddit, hooks = SubredditHooks, api = "/api/subreddits")]
pub trait SubredditRepository {
    /// SELECT * FROM subreddits WHERE slug = $1
    fn find_by_slug(slug: String) -> Vec<Subreddit>;

    /// SELECT * FROM subreddits WHERE creator_id = $1
    fn find_by_creator_id(creator_id: i64) -> Vec<Subreddit>;

    /// Race-safe get-or-insert keyed on the unique `slug` column (#1382):
    /// `find_or_create_by_slug(slug, &new) -> (Subreddit, created: bool)`.
    /// Two people submitting "r/rustlang" at once both end up on the same
    /// community with no unique-violation error — see `routes::subreddits::create`.
    fn find_or_create_by_slug(slug: String);
}

// `broadcasts = true` wires every mutation that goes through PgPostRepository
// (save/update_by_id/delete_by_id) to publish an `hx-swap-oob` fragment on the
// "posts" channel.  Clients subscribing to `/posts/events` receive live patches.
//
// `#[repository]` also unconditionally implements `M2mConnSource<Model =
// Post>` for `PgPostRepository`, which is what backs the `add_tag` /
// `remove_tag` / `set_tags` helpers generated by `Post`'s
// `#[has_many(Tag, through = post_tags)]` (#1324 many-to-many demo) -- see
// `crate::routes::posts::manage_tags`. No separate `Tag` repository is
// needed for this.
#[autumn_web::repository(Post, hooks = PostHooks, api = "/api/posts", broadcasts = true)]
pub trait PostRepository {
    /// SELECT * FROM posts WHERE slug = $1
    fn find_by_slug(slug: String) -> Vec<Post>;

    /// SELECT * FROM posts WHERE subreddit_id = $1
    fn find_by_subreddit_id(subreddit_id: i64) -> Vec<Post>;

    /// SELECT * FROM posts WHERE author_id = $1
    fn find_by_author_id(author_id: i64) -> Vec<Post>;
}

// #2260 declared a `CommentRepository` here to serve `Post`'s `dependent =
// destroy` leg. Both are gone with the `Comment` model (#1367): comments live in
// the polymorphic table now, and a `posts_delete_comments` trigger removes a
// parent's rows -- for every commentable model, not just this one.

// Typed grouped aggregate (#1364): `sum_value_grouped_by_post_id` rolls the
// votes table up to `SUM(value) GROUP BY post_id`, returning one
// `(post_id, Option<sum>)` pair per post. The front-page "Top posts by votes"
// leaderboard (`routes::posts::front_page`) chains
// `.order_by_aggregate_desc().limit(5)` for a top-N roll-up in a single call —
// a *read*, so it is replica-eligible via the repository's read route.
//
// Score maintenance is deliberately NOT this API. Since #1362 it is owned
// entirely by `Post`'s `#[votable(by = User, aggregate = sum)]`: every
// `posts.react(...)` locks the target post row, rewrites the edge, recomputes
// `SUM(value)` from ground truth and persists `posts.score` — all inside one
// transaction on the primary, so a reader never sees the edge and the score
// disagree. No route hand-writes that `UPDATE` any more (see `routes::votes`).
//
// This leaderboard is untouched by that and must stay so. `#[votable]` declares
// its own edge `table!` in a hidden private module, so `crate::schema::votes`,
// the `Vote` model and this grouped aggregate keep their nullable `post_id` —
// which is exactly what the codegen's `IS NOT NULL` group guard uses to exclude
// comment votes from the top-N. Regression-guarded by
// `leaderboard_grouped_aggregate_still_works_after_react` in
// `tests/votable_pg_integration.rs`.
//
// Checked once already: in a production-shaped fixture where post-directed
// votes were 88.1% of the table (comment votes, which this guard excludes,
// were a small minority), `post_id IS NOT NULL` was NOT selective enough —
// it matched nearly the whole table — for a partial covering index —
// `(post_id) INCLUDE (value) WHERE post_id IS NOT NULL` — to ever get
// chosen by the planner over the seq scan. That is a property of *that*
// vote mix, not a guarantee: a deployment where comment votes are a much
// larger share of `votes` would see a more selective guard (matching a
// smaller fraction of the table), and the index could earn its keep there.
// Re-measure against real data before concluding either way — don't just
// reason from this comment. See
// `docs/reports/2026-09-20-ledger-reddit-vote-leaderboard-covering-index-negative-result/`
// for the methodology and the fixture's exact ratio.
#[autumn_web::repository(Vote, table = "votes")]
pub trait VoteRepository {
    /// SUM(value) GROUP BY post_id -> `Vec<(post_id, Option<sum>)>`.
    fn sum_value_grouped_by_post_id() -> Vec<(i64, Option<i64>)>;
}

#[derive(Clone, Debug)]
pub struct PostRelationsLookup {
    pub author_name: String,
    pub sub_name: String,
    pub sub_slug: String,
}

tokio::task_local! {
    pub static CURRENT_POST_RELATIONS: PostRelationsLookup;
}

// LiveFragment renders a compact list-item fragment for each post.
// The macro uses this to build the hx-swap-oob payload when save/update/delete fires.
impl autumn_web::live::LiveFragment for Post {
    fn dom_id_for(id: i64) -> String {
        format!("post-{id}")
    }

    fn dom_id(&self) -> String {
        Self::dom_id_for(self.id)
    }

    fn render_fragment(&self) -> maud::Markup {
        let (author_name, sub_name, sub_slug) = CURRENT_POST_RELATIONS
            .try_with(|lookup| {
                (
                    lookup.author_name.clone(),
                    lookup.sub_name.clone(),
                    lookup.sub_slug.clone(),
                )
            })
            .unwrap_or_else(|_| {
                (
                    "deleted_user".to_string(),
                    "unknown".to_string(),
                    "unknown".to_string(),
                )
            });

        let card_url = format!("/r/{}/posts/{}", sub_slug, self.slug);

        maud::html! {
            li id=(self.dom_id()) class="posts-feed-item transition-all" {
                // 1. Card Layout Version
                div class="posts-feed-card-version bg-white rounded-lg shadow-sm border border-gray-200 hover:border-orange-300 transition-colors" {
                    div class="flex items-start gap-3 p-4" {
                        // The broadcast variant: no per-viewer state (there is
                        // no "current viewer" for a fragment fanned out to
                        // every subscriber), no CSRF input (SSE only reaches
                        // htmx clients, whose requests carry the token as a
                        // header via `autumn-htmx-csrf.js`), and `hx-preserve`
                        // on the buttons so this card swap never un-presses a
                        // viewer's own vote.
                        (crate::routes::layout::broadcast_vote_controls(self.id, self.score))
                        div class="flex-1 min-w-0" {
                            a href=(card_url)
                               class="text-lg font-medium text-gray-900 hover:text-orange-600 line-clamp-2" {
                                (self.title)
                            }
                            div class="text-xs text-gray-400 mt-1" {
                                a href=(format!("/r/{}", sub_slug))
                                   class="font-medium text-gray-600 hover:underline" {
                                    "r/" (sub_name)
                                }
                                " \u{2022} posted by "
                                a href=(format!("/u/{}", author_name))
                                   class="text-gray-500 hover:underline" {
                                    "u/" (author_name)
                                }
                                " " (crate::routes::layout::time_ago(&self.created_at))
                                " \u{2022} "
                                a href=(card_url)
                                   class="text-gray-500 hover:text-orange-600" {
                                    (self.comment_count) " comments"
                                }
                            }
                        }
                    }
                }

                // 2. Compact Layout Version
                div class="posts-feed-compact-version flex items-center gap-3 py-2 px-2 hover:bg-gray-50 transition-colors" {
                    span class="text-sm font-semibold text-gray-500 w-8 text-right shrink-0" {
                        (self.score)
                    }
                    div class="flex-1 min-w-0" {
                        a href=(card_url)
                           class="text-sm font-medium text-gray-900 hover:text-orange-600 line-clamp-1" {
                            (self.title)
                        }
                        div class="text-xs text-gray-400" {
                            a href=(format!("/r/{}", sub_slug))
                               class="text-gray-500 hover:underline" {
                                "r/" (sub_name)
                            }
                            " \u{2022} "
                            a href=(format!("/u/{}", author_name))
                               class="text-gray-500 hover:underline" {
                                "u/" (author_name)
                            }
                            " \u{2022} " (crate::routes::layout::time_ago(&self.created_at))
                            " \u{2022} "
                            a href=(card_url)
                               class="text-gray-500 hover:text-orange-600" {
                                (self.comment_count) " comments"
                            }
                        }
                    }
                }
            }
        }
    }

    fn insert_swap() -> autumn_web::htmx::OobSwap {
        autumn_web::htmx::OobSwap::Target(
            autumn_web::htmx::OobMethod::BeforeEnd,
            "#posts-list".to_string(),
        )
    }
}
