//! Registration types returned by macro-generated companion functions.
//!
//! `#[workflow]` generates `__autumn_workflow_info_*() -> WorkflowInfo`.
//! `#[activity]` generates `__autumn_activity_info_*() -> ActivityInfo`.
//! These are collected by `workflows![]` and `activities![]` bang macros.

use std::future::Future;
use std::pin::Pin;
use std::time::Duration;

use crate::dag::{DagBuildError, DagBuilder, DagDefinition};
use crate::policy::{RetryPolicy, Schedule};

/// Type-erased workflow handler.
///
/// Takes a `WorkflowContext` reference and serialized JSON input;
/// returns serialized JSON output (or an error string).
///
/// The macro wraps the user's typed function to handle
/// serialization/deserialization at the boundary.
pub type WorkflowHandlerFn =
    fn(
        &crate::context::WorkflowContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Type-erased activity handler.
pub type ActivityHandlerFn =
    fn(
        &crate::context::ActivityContext,
        serde_json::Value,
    ) -> Pin<Box<dyn Future<Output = Result<serde_json::Value, String>> + Send + '_>>;

/// Metadata for a registered workflow, generated by `#[workflow]`.
pub struct WorkflowInfo {
    /// Snake-case function name (e.g., `"onboarding_workflow"`).
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Type-erased dispatch function.
    pub handler: WorkflowHandlerFn,
}

/// Metadata for a registered activity, generated by `#[activity]`.
pub struct ActivityInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Default retry policy (overridable at call site).
    pub default_retry_policy: Option<RetryPolicy>,
    /// Default start-to-close timeout.
    pub default_start_to_close: Option<Duration>,
    /// Default heartbeat timeout (`None` = disabled).
    pub default_heartbeat_timeout: Option<Duration>,
    /// Default schedule-to-start timeout.
    pub default_schedule_to_start: Option<Duration>,
    /// Default task queue name (`None` = `"default"`).
    pub default_queue: Option<&'static str>,
    /// Type-erased dispatch function.
    pub handler: ActivityHandlerFn,
}

/// Metadata for a registered DAG, generated by `#[dag]`.
pub struct DagInfo {
    /// Snake-case function name.
    pub name: &'static str,
    /// `module_path!()` value from the macro call site.
    pub module: &'static str,
    /// Optional schedule for automatic runs.
    pub schedule: Option<Schedule>,
    /// Whether the scheduler should backfill missed intervals.
    pub catchup: bool,
    /// Maximum number of active runs allowed at once.
    pub max_active_runs: u32,
    /// Default queue applied to tasks that do not override their queue.
    pub default_queue: Option<&'static str>,
    /// Builder function that populates a [`DagBuilder`].
    pub builder: fn(&mut DagBuilder),
}

impl DagInfo {
    /// Build an immutable DAG definition from this metadata.
    ///
    /// # Errors
    ///
    /// Returns [`DagBuildError`] if the builder creates an invalid graph.
    pub fn build_definition(&self) -> Result<DagDefinition, DagBuildError> {
        let mut dag = match self.default_queue {
            Some(queue) => DagBuilder::with_default_queue(queue),
            None => DagBuilder::new(),
        };
        (self.builder)(&mut dag);
        dag.build()
    }
}

impl std::fmt::Debug for WorkflowInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WorkflowInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for ActivityInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ActivityInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("default_retry_policy", &self.default_retry_policy)
            .field("default_start_to_close", &self.default_start_to_close)
            .field("default_heartbeat_timeout", &self.default_heartbeat_timeout)
            .field("default_schedule_to_start", &self.default_schedule_to_start)
            .field("default_queue", &self.default_queue)
            .field("handler", &"<fn>")
            .finish()
    }
}

impl std::fmt::Debug for DagInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DagInfo")
            .field("name", &self.name)
            .field("module", &self.module)
            .field("schedule", &self.schedule)
            .field("catchup", &self.catchup)
            .field("max_active_runs", &self.max_active_runs)
            .field("default_queue", &self.default_queue)
            .field("builder", &"<fn>")
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::TriggerRule;

    #[test]
    fn workflow_info_fields_accessible() {
        let info = WorkflowInfo {
            name: "test_workflow",
            module: "my_app::workflows",
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert_eq!(info.name, "test_workflow");
    }

    #[test]
    fn activity_info_default_policy() {
        let info = ActivityInfo {
            name: "test_activity",
            module: "my_app::activities",
            default_retry_policy: None,
            default_start_to_close: None,
            default_heartbeat_timeout: None,
            default_schedule_to_start: None,
            default_queue: None,
            handler: |_ctx, input| Box::pin(async move { Ok(input) }),
        };
        assert!(info.default_retry_policy.is_none());
        assert_eq!(info.default_queue, None);
    }

    #[test]
    fn dag_info_builds_definition() {
        fn extract_users() {}
        fn load_users() {}

        fn build(dag: &mut DagBuilder) {
            let first = dag.activity(extract_users);
            let _second = dag.activity(load_users).upstream(&first);
        }

        let info = DagInfo {
            name: "daily_etl",
            module: "tests",
            schedule: Some(Schedule::Manual),
            catchup: false,
            max_active_runs: 1,
            default_queue: Some("etl-workers"),
            builder: build,
        };

        let definition = info.build_definition().expect("dag should compile");
        assert_eq!(definition.tasks().len(), 2);
        assert_eq!(definition.execution_levels().len(), 2);
        assert_eq!(definition.tasks()[0].queue.as_deref(), Some("etl-workers"));
        assert_eq!(definition.tasks()[1].trigger_rule, TriggerRule::AllSuccess);
    }
}
