-- Generated by `autumn_web::storage::migrations::add_blob_column!("users", "avatar")`.
-- See `docs/guide/storage.md` for the autumn-web side of the story.
ALTER TABLE users ADD COLUMN avatar JSONB NULL;
