server:
  port: {{get_env(name="LOCO_APP_PORT", default="8080")}}
  binding: 0.0.0.0
  host: http://localhost
  middlewares:
    limit_payload:
      enable: true
      body_limit: 5mb
    logger:
      enable: false

database:
  uri: {{get_env(name="DATABASE_URL", default="postgres://benchmark:benchmark@localhost:5432/benchmark")}}
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 20
  auto_migrate: true

logger:
  enable: true
  level: warn
  format: json
