//! Generated by `autumn generate scaffold`, then extended for the shipped bookmarks example.
//!
//! The generated scaffold provides the resource shape. The shipped example adds
//! Tailwind styling, htmx affordances, tag filtering, and local-demo writes.
//!
//! # Active Search & Autocomplete (issue #768)
//!
//! Two widget-driven routes are included to demonstrate the primitives:
//!
//! - `GET /bookmarks/search?q=…` — returns a rendered partial of matching
//!   bookmarks. The index page wires this up via [`autumn_web::widgets::active_search`].
//! - `GET /bookmarks/tags/autocomplete?q=…` — returns matching tag option
//!   partials. The new/edit forms wire this up via
//!   [`autumn_web::widgets::autocomplete_input`].
//!
//! Both handlers are ordinary Autumn route handlers that return `Markup`.
//! They own the Diesel query; the widgets own the htmx wiring.

use autumn_web::extract::{Form, Path};
use autumn_web::prelude::*;
use diesel::prelude::*;
use diesel_async::RunQueryDsl;

use crate::models::bookmark::{Bookmark, NewBookmark};
use crate::repositories::bookmark::{BookmarkRepository, PgBookmarkRepository};
use crate::schema::bookmarks;

fn layout(title: &str, content: Markup) -> Markup {
    html! {
        (autumn_web::PreEscaped("<!DOCTYPE html>"))
        html lang="en" {
            head {
                meta charset="utf-8";
                meta name="viewport" content="width=device-width, initial-scale=1";
                title { (title) " - Bookmarks" }
                link rel="stylesheet" href="/static/css/autumn.css";
                script src="/static/js/htmx.min.js" {}
            }
            body class="bg-gray-50 min-h-screen" {
                nav class="bg-indigo-600 text-white p-4" {
                    div class="max-w-3xl mx-auto flex justify-between items-center" {
                        a href="/bookmarks" class="text-xl font-bold" { "Bookmarks" }
                        div class="space-x-4 text-sm" {
                            a href="/actuator/health" class="opacity-75 hover:opacity-100" { "Health" }
                            a href="/actuator/info" class="opacity-75 hover:opacity-100" { "Info" }
                        }
                    }
                }
                main class="max-w-3xl mx-auto p-6" { (content) }
            }
        }
    }
}

fn bookmark_card(bookmark: &Bookmark) -> Markup {
    html! {
        li id=(format!("bookmark-{}", bookmark.id))
           class="p-4 bg-white rounded shadow flex justify-between items-center gap-4" {
            div {
                a href=(bookmark.url) target="_blank"
                   class="text-indigo-600 font-medium hover:underline" {
                    (bookmark.title)
                }
                a href=(format!("/bookmarks/tag/{}", bookmark.tag))
                   class="ml-2 text-xs bg-gray-200 rounded px-2 py-0.5" {
                    (bookmark.tag)
                }
                @if !bookmark.alive {
                    span class="ml-2 text-xs bg-red-100 text-red-600 rounded px-2 py-0.5" {
                        "dead link"
                    }
                }
            }
            div class="flex items-center gap-3 text-sm" {
                a href=(format!("/bookmarks/{}/edit", bookmark.id))
                   class="text-gray-500 hover:text-gray-700" {
                    "Edit"
                }
                button
                    hx-delete=(format!("/api/bookmarks/{}", bookmark.id))
                    hx-target=(format!("#bookmark-{}", bookmark.id))
                    hx-swap="outerHTML"
                    hx-confirm="Delete this bookmark?"
                    class="text-red-500 hover:text-red-700" {
                    "Delete"
                }
            }
        }
    }
}

#[get("/bookmarks")]
pub async fn index(repo: PgBookmarkRepository) -> AutumnResult<Markup> {
    let rows = repo.find_all().await?;
    let search_config = autumn_web::widgets::ActiveSearchConfig::new(
        "/bookmarks/search",
        "#bookmark-search-results",
    )
    .placeholder("Search by title, URL, or tag…")
    .debounce(400)
    .min_length(2);

    Ok(layout(
        "All",
        html! {
            div class="flex justify-between items-center mb-6" {
                h1 class="text-2xl font-bold" { "All Bookmarks" }
                a href="/bookmarks/new"
                  class="bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700" {
                    "+ Add"
                }
            }
            // ── Active search widget ──────────────────────────────────────
            div class="mb-6" {
                (autumn_web::widgets::active_search_input(
                    "bookmark-search",
                    "Search bookmarks",
                    &search_config,
                ))
            }
            // ── Results (initial list; replaced by search partial) ────────
            div id="bookmark-search-results" role="status" aria-live="polite" aria-atomic="true" {
                ul class="space-y-3" {
                    @for row in &rows {
                        (bookmark_card(row))
                    }
                    @if rows.is_empty() {
                        li class="text-gray-400 text-center py-8" { "No bookmarks yet." }
                    }
                }
            }
        },
    ))
}

#[get("/bookmarks/{id}")]
pub async fn show(id: Path<i64>, mut db: Db) -> AutumnResult<Markup> {
    let row: Bookmark = bookmarks::table
        .find(*id)
        .select(Bookmark::as_select())
        .first(&mut *db)
        .await
        .map_err(AutumnError::not_found)?;

    Ok(layout(
        &format!("Bookmark #{}", row.id),
        html! {
            div class="mb-6" {
                a href="/bookmarks" class="text-sm text-indigo-600 hover:underline" { "Back to list" }
            }
            (bookmark_card(&row))
        },
    ))
}

#[get("/bookmarks/tag/{tag}")]
pub async fn by_tag(Path(tag): Path<String>, repo: PgBookmarkRepository) -> AutumnResult<Markup> {
    let tagged = repo.find_by_tag(tag.clone()).await?;
    Ok(layout(
        &format!("#{tag}"),
        html! {
            div class="mb-6" {
                a href="/bookmarks" class="text-sm text-indigo-600 hover:underline" { "Back to all" }
                h1 class="text-2xl font-bold mt-2" { "Tag: " (tag) }
            }
            ul class="space-y-3" {
                @for row in &tagged {
                    (bookmark_card(row))
                }
                @if tagged.is_empty() {
                    li class="text-gray-400 text-center py-8" { "No bookmarks with this tag." }
                }
            }
        },
    ))
}

#[get("/bookmarks/new")]
pub async fn new_form() -> AutumnResult<Markup> {
    let tag_ac =
        autumn_web::widgets::AutocompleteConfig::new("/bookmarks/tags/autocomplete", "tag")
            .placeholder("Search existing tags…")
            .min_length(1);

    Ok(layout(
        "Add Bookmark",
        html! {
            h1 class="text-2xl font-bold mb-6" { "Add Bookmark" }
            form action="/bookmarks" method="post" class="space-y-4" {
                div {
                    label for="url" class="block text-sm font-medium" { "URL" }
                    input type="url" id="url" name="url" required
                          placeholder="https://example.com"
                          class="w-full border rounded p-2 mt-1";
                }
                div {
                    label for="title" class="block text-sm font-medium" { "Title" }
                    input type="text" id="title" name="title" required
                          placeholder="My favorite site"
                          class="w-full border rounded p-2 mt-1";
                }
                // ── Tag autocomplete ──────────────────────────────────────
                // Use the autocomplete widget to look up existing tags.
                // The hidden <input name="tag"> carries the selected value.
                // The noscript fallback renders a plain text input.
                div {
                    (autumn_web::widgets::autocomplete_input("tag-picker", "Tag", &tag_ac))
                    // Fallback for non-htmx submit: also accept direct text entry
                    noscript {
                        input type="text" id="tag" name="tag" value="general" required
                              class="w-full border rounded p-2 mt-1";
                    }
                }
                button type="submit"
                       class="bg-indigo-600 text-white px-6 py-2 rounded hover:bg-indigo-700" {
                    "Save"
                }
            }
        },
    ))
}

#[post("/bookmarks")]
pub async fn create(
    repo: PgBookmarkRepository,
    Form(new): Form<NewBookmark>,
) -> AutumnResult<Redirect> {
    repo.save(&new).await?;
    Ok(Redirect::to("/bookmarks"))
}

#[get("/bookmarks/{id}/edit")]
pub async fn edit_form(id: Path<i64>, mut db: Db) -> AutumnResult<Markup> {
    let row: Bookmark = bookmarks::table
        .find(*id)
        .select(Bookmark::as_select())
        .first(&mut *db)
        .await
        .map_err(AutumnError::not_found)?;

    Ok(layout(
        &format!("Edit Bookmark #{}", row.id),
        html! {
            h1 class="text-2xl font-bold mb-6" { "Edit Bookmark" }
            form action=(format!("/bookmarks/{}/update", row.id)) method="post" class="space-y-4" {
                div {
                    label for="url" class="block text-sm font-medium" { "URL" }
                    input type="url" id="url" name="url" required
                          value=(row.url)
                          class="w-full border rounded p-2 mt-1";
                }
                div {
                    label for="title" class="block text-sm font-medium" { "Title" }
                    input type="text" id="title" name="title" required
                          value=(row.title)
                          class="w-full border rounded p-2 mt-1";
                }
                div {
                    label for="tag" class="block text-sm font-medium" { "Tag" }
                    input type="text" id="tag" name="tag" required
                          value=(row.tag)
                          class="w-full border rounded p-2 mt-1";
                }
                button type="submit"
                       class="bg-indigo-600 text-white px-6 py-2 rounded hover:bg-indigo-700" {
                    "Save"
                }
            }
        },
    ))
}

#[post("/bookmarks/{id}/update")]
pub async fn update(
    id: Path<i64>,
    mut db: Db,
    Form(form): Form<NewBookmark>,
) -> AutumnResult<Redirect> {
    let updated = diesel::update(bookmarks::table.find(*id))
        .set((
            bookmarks::url.eq(form.url.clone()),
            bookmarks::title.eq(form.title.clone()),
            bookmarks::tag.eq(form.tag.clone()),
        ))
        .execute(&mut *db)
        .await?;

    if updated == 0 {
        return Err(AutumnError::not_found_msg(format!(
            "Bookmark with id {} not found",
            *id
        )));
    }

    Ok(Redirect::to(&format!("/bookmarks/{}", *id)))
}

// ── Active search handler ─────────────────────────────────────────────────────

#[derive(serde::Deserialize)]
pub struct SearchQuery {
    #[serde(default)]
    pub q: String,
}

/// Active search handler — returns a `<ul>` partial of matching bookmarks.
///
/// Wired up by [`autumn_web::widgets::active_search_input`] on the index page.
/// Works equally well without JavaScript (direct GET form submission).
#[get("/bookmarks/search")]
pub async fn search(Query(params): Query<SearchQuery>, mut db: Db) -> AutumnResult<Markup> {
    let q = params.q.trim();
    if q.chars().count() < 2 {
        return Ok(autumn_web::widgets::active_search_empty_state(
            "Enter at least two characters to search.",
        ));
    }

    let pattern = format!("%{q}%");
    let results: Vec<Bookmark> = bookmarks::table
        .filter(
            bookmarks::title
                .ilike(pattern.clone())
                .or(bookmarks::url.ilike(pattern.clone()))
                .or(bookmarks::tag.ilike(pattern)),
        )
        .select(Bookmark::as_select())
        .load(&mut *db)
        .await?;

    Ok(html! {
        @if results.is_empty() {
            (autumn_web::widgets::active_search_empty_state("No bookmarks match your search."))
        } @else {
            ul class="space-y-3" {
                @for row in &results {
                    (bookmark_card(row))
                }
            }
        }
    })
}

// ── Tag autocomplete handler ──────────────────────────────────────────────────

/// Tag autocomplete handler — returns option partials for matching tags.
///
/// Wired up by [`autumn_web::widgets::autocomplete_input`] on the new/edit forms.
#[get("/bookmarks/tags/autocomplete")]
pub async fn tags_autocomplete(
    Query(params): Query<SearchQuery>,
    mut db: Db,
) -> AutumnResult<Markup> {
    let q = params.q.trim();
    if q.is_empty() {
        return Ok(autumn_web::widgets::autocomplete_empty_state(
            "Type to search tags.",
        ));
    }

    let pattern = format!("%{q}%");
    let tags: Vec<String> = bookmarks::table
        .select(bookmarks::tag)
        .filter(bookmarks::tag.ilike(pattern))
        .distinct()
        .order(bookmarks::tag.asc())
        .load(&mut *db)
        .await?;

    Ok(html! {
        @if tags.is_empty() {
            (autumn_web::widgets::autocomplete_empty_state("No matching tags found."))
        } @else {
            @for tag in &tags {
                (autumn_web::widgets::autocomplete_option(tag, tag))
            }
        }
    })
}
