//! Generated by `autumn generate scaffold`.
//!
//! `#[repository]` auto-generates CRUD methods and JSON REST handlers. The
//! scaffold registers only read handlers in `src/main.rs` by
//! default. Mount mutating API handlers only after adding a policy.

use crate::models::bookmark::{Bookmark, NewBookmark, UpdateBookmark};
use crate::schema::bookmarks;

#[autumn_web::repository(Bookmark, api = "/api/bookmarks")]
pub trait BookmarkRepository {
    fn find_by_tag(tag: String) -> Vec<Bookmark>;
    fn find_by_alive(alive: bool) -> Vec<Bookmark>;
}
