//! Smoke test generated by `autumn generate scaffold`.
//!
//! Hit the route on a real server by setting `AUTUMN_TEST_BASE_URL`.

#[test]
fn bookmarks_index_returns_200_when_server_is_running() {
    let Ok(base) = std::env::var("AUTUMN_TEST_BASE_URL") else {
        eprintln!("skipping: AUTUMN_TEST_BASE_URL not set");
        return;
    };

    let base = base.trim_end_matches('/');
    let url = format!("{base}/bookmarks");
    let host_port = base
        .trim_start_matches("http://")
        .trim_start_matches("https://");
    let mut stream = std::net::TcpStream::connect(host_port)
        .unwrap_or_else(|_| panic!("could not connect to {url}"));

    use std::io::{Read, Write};
    let req = format!("GET /bookmarks HTTP/1.1\r\nHost: {host_port}\r\nConnection: close\r\n\r\n");
    stream.write_all(req.as_bytes()).expect("write failed");

    let mut response = String::new();
    stream.read_to_string(&mut response).expect("read failed");
    assert!(
        response.starts_with("HTTP/1.1 200") || response.starts_with("HTTP/1.0 200"),
        "Bookmark index did not return 200:\n{response}"
    );
    assert!(
        response.contains("Bookmarks"),
        "Bookmark index did not render the generated template:\n{response}"
    );
}
