DROP TRIGGER IF EXISTS _autumn_money_postings_no_truncate ON _autumn_money_postings;
DROP TRIGGER IF EXISTS _autumn_money_transactions_no_truncate ON _autumn_money_transactions;
DROP TRIGGER IF EXISTS _autumn_money_postings_append_only ON _autumn_money_postings;
DROP TRIGGER IF EXISTS _autumn_money_transactions_append_only ON _autumn_money_transactions;
DROP TRIGGER IF EXISTS _autumn_money_accounts_currency_fixed ON _autumn_money_accounts;
DROP FUNCTION IF EXISTS _autumn_money_append_only();
DROP FUNCTION IF EXISTS _autumn_money_currency_is_fixed();
DROP TABLE IF EXISTS _autumn_money_postings;
DROP TABLE IF EXISTS _autumn_money_transactions;
DROP TABLE IF EXISTS _autumn_money_accounts;
