ALTER TABLE api_tokens DROP COLUMN IF EXISTS last_used_at;
ALTER TABLE api_tokens DROP COLUMN IF EXISTS expires_at;
ALTER TABLE api_tokens DROP COLUMN IF EXISTS scopes;
ALTER TABLE api_tokens DROP COLUMN IF EXISTS name;
