// A full versioned repository over a model with encrypted columns must compile:
// insert, update, bulk, upsert, and version-history composition all work with
// the diesel serialize_as/deserialize_as wrappers.

use autumn_web::model;
use autumn_web::repository;

diesel::table! {
    vault_entries (id) {
        id -> Int8,
        label -> Text,
        secret -> Text,
        lookup_key -> Text,
    }
}

#[model(table = "vault_entries")]
pub struct VaultEntry {
    #[id]
    pub id: i64,
    pub label: String,
    #[encrypted]
    pub secret: String,
    #[encrypted(deterministic)]
    pub lookup_key: String,
}

#[repository(VaultEntry, table = "vault_entries", versioned = true)]
pub trait VaultEntryRepository {
    // Derived equality lookups: the deterministic-encrypted `lookup_key` routes
    // its String param through the runtime registry encoder, and the plaintext
    // `label` passes through. Both must generate compiling code (#805).
    // (`find_by_id` is auto-generated by the macro, so it is not redeclared here.)
    fn find_by_lookup_key(lookup_key: String) -> Vec<VaultEntry>;
    fn count_by_lookup_key(lookup_key: String) -> i64;
    fn exists_by_lookup_key(lookup_key: String) -> bool;
    fn find_by_label(label: String) -> Vec<VaultEntry>;
}

fn main() {}
