//! # Autumn
//!
//! An opinionated, convention-over-configuration web framework for Rust.
//!
//! Autumn assembles proven Rust crates (Axum, Maud, Tailwind, htmx, Diesel)
//! into a Spring Boot-style developer experience with proc-macro-driven
//! conventions and escape hatches at every level.

pub mod config;
pub mod route;

// Re-export route macros so users can write `use autumn::get;`
pub use autumn_macros::{delete, get, post, put};

/// Re-exports of upstream crates used in macro-generated code.
///
/// These are public so that code generated by `autumn-macros` can reference
/// them as `autumn::reexports::axum`, etc. Users should prefer the
/// `autumn::prelude` module (coming in a later story) over reaching
/// into reexports directly.
pub mod reexports {
    pub use axum;
    pub use http;
}

/// Shared application state passed to all route handlers.
///
/// Placeholder for v0.1 — the real `AppState` will hold config, database
/// pool, and other framework-managed resources (S-009).
#[derive(Clone, Debug)]
pub struct AppState;
