//! # Autumn
//!
//! An opinionated, convention-over-configuration web framework for Rust.
//!
//! Autumn assembles proven Rust crates (Axum, Maud, Tailwind, htmx, Diesel)
//! into a Spring Boot-style developer experience with proc-macro-driven
//! conventions and escape hatches at every level.

pub mod app;
pub mod config;
pub mod db;
pub mod error;
pub mod extract;
pub mod health;
pub(crate) mod htmx;
pub mod logging;
pub mod middleware;
pub mod route;

pub use app::app;
pub use db::Db;
pub use error::{AutumnError, AutumnResult};
pub use htmx::HTMX_VERSION;

// Re-export proc macros so users can write `use autumn::get;` or `#[autumn::main]`
pub use autumn_macros::{delete, get, main, model, post, put, routes};

// Re-export Maud types for HTML rendering
pub use maud::{Markup, PreEscaped, html};

// Re-export Json at root level (commonly used in return types)
pub use axum::Json;

/// Re-exports of upstream crates used in macro-generated code.
///
/// These are public so that code generated by `autumn-macros` can reference
/// them as `autumn::reexports::axum`, etc. Users should prefer the
/// `autumn::prelude` module (coming in a later story) over reaching
/// into reexports directly.
pub mod reexports {
    pub use axum;
    pub use diesel;
    pub use http;
    pub use tokio;
}

/// Shared application state passed to all route handlers.
///
/// Holds framework-managed resources such as the optional database
/// connection pool. Axum requires `Clone`, so internal resources
/// use `Arc` or are already cheaply cloneable (deadpool `Pool` is
/// `Arc`-wrapped internally).
#[derive(Clone)]
pub struct AppState {
    /// Database connection pool. `None` when no `database.url` is configured.
    pub pool:
        Option<diesel_async::pooled_connection::deadpool::Pool<diesel_async::AsyncPgConnection>>,
}

impl std::fmt::Debug for AppState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AppState")
            .field(
                "pool",
                &self
                    .pool
                    .as_ref()
                    .map(|p| format!("Pool(max={})", p.status().max_size)),
            )
            .finish()
    }
}
