//! Typed path helpers for building URL paths at compile time.
//!
//! Each `#[get]` / `#[post]` / `#[put]` / `#[delete]` / `#[patch]` route
//! macro emits a `__autumn_path_{name}` companion function alongside the
//! handler. The [`paths![]`](crate::paths) collection macro gathers these
//! into a `pub mod paths { ... }` block, giving callers a stable,
//! compiler-checked surface:
//!
//! ```rust,ignore
//! use crate::paths;
//!
//! // Before (stringly-typed, breaks silently on rename):
//! let url = format!("/posts/{}", post.id);
//!
//! // After (typed, breaks loudly on rename):
//! let url = paths::show_post(post.id).to_string();
//! ```
//!
//! ## Query strings
//!
//! [`PathBuilder::with_query`] appends percent-encoded key-value pairs:
//!
//! ```rust,ignore
//! let url = paths::list_posts()
//!     .with_query("page", 2)
//!     .with_query("per_page", 20)
//!     .to_string(); // "/posts?page=2&per_page=20"
//! ```
//!
//! ## Redirects
//!
//! [`PathBuilder::into_redirect`] converts a built path into an
//! [`axum::response::Redirect`] for use in route handlers:
//!
//! ```rust,ignore
//! return paths::show_post(post.id).into_redirect();
//! ```

use std::fmt;
use std::ops::Deref;

use percent_encoding::{AsciiSet, CONTROLS, utf8_percent_encode};

/// Encoding set for query-string keys and values.
///
/// Keeps RFC 3986 unreserved characters (`A-Z a-z 0-9 - . _ ~`) unencoded and
/// percent-encodes everything else, including `&`, `=`, `+`, `?`, `#`, and
/// space, which are all meaningful in a query string context.
const QUERY_COMPONENT: &AsciiSet = &CONTROLS
    .add(b' ')
    .add(b'"')
    .add(b'#')
    .add(b'%')
    .add(b'<')
    .add(b'>')
    .add(b'[')
    .add(b'\\')
    .add(b']')
    .add(b'^')
    .add(b'`')
    .add(b'{')
    .add(b'|')
    .add(b'}')
    .add(b'!')
    .add(b'$')
    .add(b'&')
    .add(b'\'')
    .add(b'(')
    .add(b')')
    .add(b'*')
    .add(b'+')
    .add(b',')
    .add(b';')
    .add(b'=')
    .add(b'?')
    .add(b'/')
    .add(b':')
    .add(b'@');

/// A built URL path with optional query-string support.
///
/// Returned by every path helper generated by the route macros.  Derefs to
/// `&str`, converts to `String`, and can be chained with
/// [`with_query`](Self::with_query) to append percent-encoded query pairs.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathBuilder(String);

impl PathBuilder {
    /// Wrap a pre-formatted path string.
    #[must_use]
    pub fn new(path: String) -> Self {
        PathBuilder(path)
    }

    /// Append a percent-encoded `key=value` query parameter.
    ///
    /// The first call inserts `?`; subsequent calls insert `&`.
    /// Both key and value are percent-encoded using
    /// [`percent_encoding::NON_ALPHANUMERIC`] for maximum safety.
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// let url = paths::list_posts()
    ///     .with_query("page", 2)
    ///     .with_query("tag", "rust web")
    ///     .to_string();
    /// // "/posts?page=2&tag=rust%20web"
    /// ```
    #[must_use]
    pub fn with_query(mut self, key: &str, value: impl fmt::Display) -> Self {
        let sep = if self.0.contains('?') { '&' } else { '?' };
        let key_str = key.to_owned();
        let val_str = value.to_string();
        let encoded_key = utf8_percent_encode(&key_str, QUERY_COMPONENT);
        let encoded_val = utf8_percent_encode(&val_str, QUERY_COMPONENT);
        self.0.push(sep);
        self.0.push_str(&encoded_key.to_string());
        self.0.push('=');
        self.0.push_str(&encoded_val.to_string());
        self
    }

    /// Convert this path helper into an [`axum::response::Redirect`].
    ///
    /// This avoids the `&str`/`String` dance when returning from a handler:
    ///
    /// ```rust,ignore
    /// return paths::show_post(post.id).into_redirect();
    /// ```
    pub fn into_redirect(self) -> axum::response::Redirect {
        axum::response::Redirect::to(&self.0)
    }
}

impl fmt::Display for PathBuilder {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl Deref for PathBuilder {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<PathBuilder> for String {
    fn from(pb: PathBuilder) -> Self {
        pb.0
    }
}

impl AsRef<str> for PathBuilder {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

/// Allow `PathBuilder` to be used directly inside `html! { }` Maud templates.
///
/// The value is HTML-escaped exactly like a `&str` would be, so special
/// characters in query-string values (e.g. `<`, `>`, `&`) are safe.
#[cfg(feature = "maud")]
impl maud::Render for PathBuilder {
    fn render_to(&self, buffer: &mut String) {
        maud::Render::render_to(self.0.as_str(), buffer)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_stores_path() {
        let pb = PathBuilder::new("/posts".to_owned());
        assert_eq!(pb.to_string(), "/posts");
    }

    #[test]
    fn with_query_first_call_uses_question_mark() {
        let pb = PathBuilder::new("/posts".to_owned()).with_query("page", 2);
        assert_eq!(pb.to_string(), "/posts?page=2");
    }

    #[test]
    fn with_query_second_call_uses_ampersand() {
        let pb = PathBuilder::new("/posts".to_owned())
            .with_query("page", 2)
            .with_query("per_page", 10);
        assert!(pb.to_string().contains("page=2"));
        assert!(pb.to_string().contains("per_page=10"));
    }

    #[test]
    fn with_query_percent_encodes_spaces() {
        let pb = PathBuilder::new("/posts".to_owned()).with_query("q", "hello world");
        assert!(pb.to_string().contains("hello%20world"));
    }

    #[test]
    fn with_query_percent_encodes_ampersand_in_value() {
        let pb = PathBuilder::new("/posts".to_owned()).with_query("tags", "rust&web");
        assert!(pb.to_string().contains("rust%26web"));
    }

    #[test]
    fn deref_to_str() {
        let pb = PathBuilder::new("/posts".to_owned());
        assert_eq!(&*pb, "/posts");
    }

    #[test]
    fn into_string() {
        let s: String = PathBuilder::new("/posts".to_owned()).into();
        assert_eq!(s, "/posts");
    }
}
